package cli

import (
	"bytes"
	"context"
	"strings"
	"testing"

	"github.com/fyne-coder/gongcli_mcp/internal/store/postgres"
)

func TestMCPPostgresReaderSQLBusinessPilot(t *testing.T) {
	t.Parallel()

	var stdout bytes.Buffer
	var stderr bytes.Buffer
	code := Run(context.Background(), []string{
		"mcp", "postgres-reader-sql",
		"--preset", "business-pilot",
		"--role", "gongmcp_business_pilot_reader",
		"--database", "gongctl",
	}, &stdout, &stderr)
	if code != 0 {
		t.Fatalf("Run(mcp postgres-reader-sql) code=%d stderr=%q", code, stderr.String())
	}
	sql := stdout.String()
	for _, want := range []string{
		`-- Generated by gongctl mcp postgres-reader-sql.`,
		`-- Apply to a fresh NOINHERIT role; revoke stale table/function grants before reusing an existing role.`,
		`not an analyst SQL login`,
		`minimized operational metadata`,
		`profile-backed`,
		`GRANT CONNECT ON DATABASE "gongctl" TO "gongmcp_business_pilot_reader";`,
		`REVOKE CREATE ON SCHEMA "public" FROM PUBLIC;`,
		`REVOKE EXECUTE ON FUNCTION public.gongmcp_active_business_profile() FROM "gongmcp_business_pilot_reader";`,
		`REVOKE EXECUTE ON FUNCTION public.gongmcp_profile_call_fact_cache(bigint, text) FROM "gongmcp_business_pilot_reader";`,
		`REVOKE EXECUTE ON FUNCTION public.gongmcp_profile_call_fact_cache_sanitized(bigint, text) FROM "gongmcp_business_pilot_reader";`,
		`GRANT SELECT ("context_present", "parties_count", "started_at") ON TABLE public."calls" TO "gongmcp_business_pilot_reader";`,
		`GRANT SELECT ("transcript_status") ON TABLE public."call_facts" TO "gongmcp_business_pilot_reader";`,
		`GRANT EXECUTE ON FUNCTION public.gongmcp_active_business_profile_sanitized() TO "gongmcp_business_pilot_reader";`,
		`GRANT EXECUTE ON FUNCTION public.gongmcp_profile_call_fact_cache_meta_sanitized(bigint) TO "gongmcp_business_pilot_reader";`,
		`GRANT EXECUTE ON FUNCTION public.gongmcp_profile_call_fact_cache_sanitized_limited(bigint, text, integer) TO "gongmcp_business_pilot_reader";`,
		`GRANT EXECUTE ON FUNCTION public.gongmcp_profile_call_fact_summary_sanitized(bigint, text, text, text, text, text, text, text, integer) TO "gongmcp_business_pilot_reader";`,
		`COMMIT;`,
	} {
		if !strings.Contains(sql, want) {
			t.Fatalf("generated SQL missing %q\n%s", want, sql)
		}
	}
	for _, forbidden := range []string{
		`PASSWORD`,
		`CREATE ROLE`,
		`postgres://`,
		`GONG_DATABASE_URL`,
		`GRANT EXECUTE ON FUNCTION public.gongmcp_active_business_profile()`,
		`GRANT EXECUTE ON FUNCTION public.gongmcp_profile_call_fact_cache(bigint, text)`,
		`GRANT EXECUTE ON FUNCTION public.gongmcp_profile_call_fact_cache_meta(bigint, text)`,
		`GRANT EXECUTE ON FUNCTION public.gongmcp_profile_call_fact_cache_sanitized(bigint, text)`,
		`GRANT EXECUTE ON FUNCTION public.gongmcp_profile_call_fact_summary(bigint, text, text, text, text, text, text, text, integer)`,
		`"call_id") ON TABLE public."calls"`,
		`"title") ON TABLE public."calls"`,
		`"call_id") ON TABLE public."call_facts"`,
		`"title") ON TABLE public."call_facts"`,
		`"call_id"`,
		`"object_key"`,
		`public.gongmcp_missing_transcripts`,
	} {
		if strings.Contains(sql, forbidden) {
			t.Fatalf("generated SQL contained forbidden %q\n%s", forbidden, sql)
		}
	}
	if stderr.Len() != 0 {
		t.Fatalf("stderr not empty: %q", stderr.String())
	}
}

func TestMCPPostgresReaderSQLRejectsUnsupportedPreset(t *testing.T) {
	t.Parallel()

	var stdout bytes.Buffer
	var stderr bytes.Buffer
	code := Run(context.Background(), []string{
		"mcp", "postgres-reader-sql",
		"--preset", "operator-smoke",
	}, &stdout, &stderr)
	if code != 1 {
		t.Fatalf("Run unsupported preset code=%d want 1 stderr=%q", code, stderr.String())
	}
	if stdout.Len() != 0 {
		t.Fatalf("stdout not empty: %q", stdout.String())
	}
	if !strings.Contains(stderr.String(), "business-pilot scoped reader surface") {
		t.Fatalf("stderr=%q missing unsupported preset message", stderr.String())
	}
}

func TestMCPPostgresReaderApplyDryRunPrintsSQLWithoutURL(t *testing.T) {
	t.Parallel()

	var stdout bytes.Buffer
	var stderr bytes.Buffer
	code := Run(context.Background(), []string{
		"mcp", "postgres-reader-apply",
		"--preset", "business-pilot",
		"--role", "gongmcp_business_pilot_reader",
		"--database", "gongctl",
	}, &stdout, &stderr)
	if code != 0 {
		t.Fatalf("Run(mcp postgres-reader-apply dry-run) code=%d stderr=%q", code, stderr.String())
	}
	sql := stdout.String()
	for _, want := range []string{
		`-- Generated by gongctl mcp postgres-reader-apply.`,
		`GRANT CONNECT ON DATABASE "gongctl" TO "gongmcp_business_pilot_reader";`,
		`REVOKE CREATE ON SCHEMA "public" FROM PUBLIC;`,
		`REVOKE EXECUTE ON FUNCTION public.gongmcp_profile_call_fact_cache_sanitized(bigint, text) FROM "gongmcp_business_pilot_reader";`,
		`GRANT EXECUTE ON FUNCTION public.gongmcp_profile_call_fact_cache_sanitized_limited(bigint, text, integer) TO "gongmcp_business_pilot_reader";`,
		`COMMIT;`,
	} {
		if !strings.Contains(sql, want) {
			t.Fatalf("generated SQL missing %q\n%s", want, sql)
		}
	}
	for _, forbidden := range []string{
		`PASSWORD`,
		`postgres://`,
		`GONG_DATABASE_URL`,
		`GRANT EXECUTE ON FUNCTION public.gongmcp_profile_call_fact_cache(bigint, text)`,
		`GRANT EXECUTE ON FUNCTION public.gongmcp_profile_call_fact_cache_sanitized(bigint, text)`,
		`"call_id"`,
		`"object_key"`,
	} {
		if strings.Contains(sql, forbidden) {
			t.Fatalf("generated SQL contained forbidden %q\n%s", forbidden, sql)
		}
	}
	if stderr.Len() != 0 {
		t.Fatalf("stderr not empty: %q", stderr.String())
	}
}

func TestMCPPostgresReaderApplyRequiresURLWithApply(t *testing.T) {
	t.Setenv("GONG_DATABASE_URL", "")
	t.Setenv("DATABASE_URL", "")

	var stdout bytes.Buffer
	var stderr bytes.Buffer
	code := Run(context.Background(), []string{
		"mcp", "postgres-reader-apply",
		"--preset", "business-pilot",
		"--apply",
	}, &stdout, &stderr)
	if code != 1 {
		t.Fatalf("Run(mcp postgres-reader-apply --apply) code=%d want 1 stderr=%q", code, stderr.String())
	}
	if stdout.Len() != 0 {
		t.Fatalf("stdout not empty: %q", stdout.String())
	}
	if !strings.Contains(stderr.String(), "GONG_DATABASE_URL or DATABASE_URL is required with --apply") {
		t.Fatalf("stderr=%q missing URL requirement", stderr.String())
	}
}

func TestMCPPostgresReaderApplyRejectsDryRunAndApply(t *testing.T) {
	t.Parallel()

	var stdout bytes.Buffer
	var stderr bytes.Buffer
	code := Run(context.Background(), []string{
		"mcp", "postgres-reader-apply",
		"--preset", "business-pilot",
		"--dry-run",
		"--apply",
	}, &stdout, &stderr)
	if code != 1 {
		t.Fatalf("Run(mcp postgres-reader-apply --dry-run --apply) code=%d want 1 stderr=%q", code, stderr.String())
	}
	if !strings.Contains(stderr.String(), "--apply and --dry-run cannot be used together") {
		t.Fatalf("stderr=%q missing flag conflict", stderr.String())
	}
}

func TestMCPPostgresReaderApplyRejectsUnsupportedPreset(t *testing.T) {
	t.Parallel()

	var stdout bytes.Buffer
	var stderr bytes.Buffer
	code := Run(context.Background(), []string{
		"mcp", "postgres-reader-apply",
		"--preset", "operator-smoke",
	}, &stdout, &stderr)
	if code != 1 {
		t.Fatalf("Run unsupported preset code=%d want 1 stderr=%q", code, stderr.String())
	}
	if stdout.Len() != 0 {
		t.Fatalf("stdout not empty: %q", stdout.String())
	}
	if !strings.Contains(stderr.String(), "business-pilot scoped reader surface") {
		t.Fatalf("stderr=%q missing unsupported preset message", stderr.String())
	}
}

func TestMCPPostgresReaderApplyRejectsUnsafeIdentifier(t *testing.T) {
	t.Parallel()

	var stdout bytes.Buffer
	var stderr bytes.Buffer
	code := Run(context.Background(), []string{
		"mcp", "postgres-reader-apply",
		"--preset", "business-pilot",
		"--role", "gongmcp_reader;DROP",
	}, &stdout, &stderr)
	if code != 1 {
		t.Fatalf("Run unsafe role code=%d want 1 stderr=%q", code, stderr.String())
	}
	if stdout.Len() != 0 {
		t.Fatalf("stdout not empty: %q", stdout.String())
	}
	if !strings.Contains(stderr.String(), "invalid role name") {
		t.Fatalf("stderr=%q missing invalid role message", stderr.String())
	}
}

func TestMCPPostgresReaderApplySuccessJSONOmitsURL(t *testing.T) {
	t.Setenv("GONG_DATABASE_URL", "postgres://writer:secret@127.0.0.1:5432/gongctl?sslmode=disable")
	t.Setenv("DATABASE_URL", "")
	orig := mcpApplyScopedReaderGrants
	t.Cleanup(func() { mcpApplyScopedReaderGrants = orig })
	var called bool
	mcpApplyScopedReaderGrants = func(ctx context.Context, databaseURL string, params postgres.ScopedReaderGrantSQLParams) (string, error) {
		called = true
		if databaseURL != "postgres://writer:secret@127.0.0.1:5432/gongctl?sslmode=disable" {
			t.Fatalf("databaseURL=%q", databaseURL)
		}
		if params.RoleName != "gongmcp_business_pilot_reader" || params.DatabaseName != "gongctl" {
			t.Fatalf("params=%+v", params)
		}
		return postgres.BuildScopedReaderGrantSQL(params)
	}

	var stdout bytes.Buffer
	var stderr bytes.Buffer
	code := Run(context.Background(), []string{
		"mcp", "postgres-reader-apply",
		"--preset", "business-pilot",
		"--role", "gongmcp_business_pilot_reader",
		"--database", "gongctl",
		"--apply",
	}, &stdout, &stderr)
	if code != 0 {
		t.Fatalf("Run(mcp postgres-reader-apply --apply) code=%d stderr=%q", code, stderr.String())
	}
	if !called {
		t.Fatal("apply function was not called")
	}
	body := stdout.String()
	for _, want := range []string{
		`"backend": "postgres"`,
		`"preset": "business-pilot"`,
		`"role": "gongmcp_business_pilot_reader"`,
		`"database": "gongctl"`,
		`"status": "applied"`,
		`"applied": true`,
		`"credential_note": "database_url_not_exported"`,
		`"role_note": "existing_role_only_passwords_managed_externally"`,
	} {
		if !strings.Contains(body, want) {
			t.Fatalf("apply JSON missing %q\n%s", want, body)
		}
	}
	for _, forbidden := range []string{
		`postgres://`,
		`writer`,
		`writer:secret`,
		`127.0.0.1`,
		`GRANT `,
		`PASSWORD`,
	} {
		if strings.Contains(body, forbidden) {
			t.Fatalf("apply JSON contained forbidden %q\n%s", forbidden, body)
		}
	}
	if stderr.Len() != 0 {
		t.Fatalf("stderr not empty: %q", stderr.String())
	}
}
