package cli

import (
	"bytes"
	"context"
	"strings"
	"testing"
)

func TestMCPPostgresReaderSQLBusinessPilot(t *testing.T) {
	t.Parallel()

	var stdout bytes.Buffer
	var stderr bytes.Buffer
	code := Run(context.Background(), []string{
		"mcp", "postgres-reader-sql",
		"--preset", "business-pilot",
		"--role", "gongmcp_business_pilot_reader",
		"--database", "gongctl",
	}, &stdout, &stderr)
	if code != 0 {
		t.Fatalf("Run(mcp postgres-reader-sql) code=%d stderr=%q", code, stderr.String())
	}
	sql := stdout.String()
	for _, want := range []string{
		`-- Generated by gongctl mcp postgres-reader-sql.`,
		`GRANT CONNECT ON DATABASE "gongctl" TO "gongmcp_business_pilot_reader";`,
		`GRANT SELECT ("parties_count", "started_at") ON TABLE "calls" TO "gongmcp_business_pilot_reader";`,
		`GRANT SELECT ("transcript_status") ON TABLE "call_facts" TO "gongmcp_business_pilot_reader";`,
		`GRANT EXECUTE ON FUNCTION public.gongmcp_profile_call_fact_summary(bigint, text, text, text, text, text, text, text, integer) TO "gongmcp_business_pilot_reader";`,
		`COMMIT;`,
	} {
		if !strings.Contains(sql, want) {
			t.Fatalf("generated SQL missing %q\n%s", want, sql)
		}
	}
	for _, forbidden := range []string{
		`PASSWORD`,
		`postgres://`,
		`GONG_DATABASE_URL`,
		`"call_id") ON TABLE "calls"`,
		`"title") ON TABLE "calls"`,
		`"call_id") ON TABLE "call_facts"`,
		`"title") ON TABLE "call_facts"`,
		`public.gongmcp_missing_transcripts`,
	} {
		if strings.Contains(sql, forbidden) {
			t.Fatalf("generated SQL contained forbidden %q\n%s", forbidden, sql)
		}
	}
	if stderr.Len() != 0 {
		t.Fatalf("stderr not empty: %q", stderr.String())
	}
}

func TestMCPPostgresReaderSQLCreateRoleDoesNotCreateCredentials(t *testing.T) {
	t.Parallel()

	var stdout bytes.Buffer
	var stderr bytes.Buffer
	code := Run(context.Background(), []string{
		"mcp", "postgres-reader-sql",
		"--preset", "business-pilot",
		"--role", "gongmcp_business_pilot_reader",
		"--database", "gongctl",
		"--create-role",
	}, &stdout, &stderr)
	if code != 0 {
		t.Fatalf("Run(mcp postgres-reader-sql --create-role) code=%d stderr=%q", code, stderr.String())
	}
	sql := stdout.String()
	if !strings.Contains(sql, `CREATE ROLE "gongmcp_business_pilot_reader" LOGIN;`) {
		t.Fatalf("generated SQL missing CREATE ROLE LOGIN\n%s", sql)
	}
	if strings.Contains(sql, "PASSWORD") {
		t.Fatalf("generated SQL should not include credentials\n%s", sql)
	}
}

func TestMCPPostgresReaderSQLRejectsUnsupportedPreset(t *testing.T) {
	t.Parallel()

	var stdout bytes.Buffer
	var stderr bytes.Buffer
	code := Run(context.Background(), []string{
		"mcp", "postgres-reader-sql",
		"--preset", "operator-smoke",
	}, &stdout, &stderr)
	if code != 1 {
		t.Fatalf("Run unsupported preset code=%d want 1 stderr=%q", code, stderr.String())
	}
	if stdout.Len() != 0 {
		t.Fatalf("stdout not empty: %q", stdout.String())
	}
	if !strings.Contains(stderr.String(), "business-pilot scoped reader surface") {
		t.Fatalf("stderr=%q missing unsupported preset message", stderr.String())
	}
}
