package postgres

var migrations = []string{
	`
CREATE TABLE IF NOT EXISTS gongctl_schema_migrations (
	version INTEGER PRIMARY KEY,
	applied_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sync_runs (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	scope TEXT NOT NULL,
	sync_key TEXT NOT NULL DEFAULT '',
	cursor TEXT NOT NULL DEFAULT '',
	from_value TEXT NOT NULL DEFAULT '',
	to_value TEXT NOT NULL DEFAULT '',
	request_context TEXT NOT NULL DEFAULT '',
	status TEXT NOT NULL,
	started_at TEXT NOT NULL,
	finished_at TEXT,
	records_seen BIGINT NOT NULL DEFAULT 0,
	records_written BIGINT NOT NULL DEFAULT 0,
	error_text TEXT NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_pg_sync_runs_scope_started_at ON sync_runs(scope, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_pg_sync_runs_status ON sync_runs(status);

CREATE TABLE IF NOT EXISTS sync_state (
	sync_key TEXT PRIMARY KEY,
	scope TEXT NOT NULL,
	cursor TEXT NOT NULL DEFAULT '',
	last_run_id BIGINT,
	last_status TEXT NOT NULL,
	last_error TEXT NOT NULL DEFAULT '',
	last_success_at TEXT,
	updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_pg_sync_state_scope ON sync_state(scope);

CREATE TABLE IF NOT EXISTS calls (
	call_id TEXT PRIMARY KEY,
	title TEXT NOT NULL DEFAULT '',
	started_at TEXT NOT NULL DEFAULT '',
	duration_seconds BIGINT NOT NULL DEFAULT 0,
	parties_count BIGINT NOT NULL DEFAULT 0,
	context_present BOOLEAN NOT NULL DEFAULT false,
	raw_json JSONB NOT NULL,
	raw_sha256 TEXT NOT NULL,
	first_seen_at TEXT NOT NULL,
	updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_pg_calls_started_at ON calls(started_at DESC);

CREATE TABLE IF NOT EXISTS users (
	user_id TEXT PRIMARY KEY,
	email TEXT NOT NULL DEFAULT '',
	first_name TEXT NOT NULL DEFAULT '',
	last_name TEXT NOT NULL DEFAULT '',
	display_name TEXT NOT NULL DEFAULT '',
	title TEXT NOT NULL DEFAULT '',
	active BOOLEAN NOT NULL DEFAULT false,
	raw_json JSONB NOT NULL,
	raw_sha256 TEXT NOT NULL,
	first_seen_at TEXT NOT NULL,
	updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_pg_users_email ON users(email);

CREATE TABLE IF NOT EXISTS transcripts (
	call_id TEXT PRIMARY KEY,
	raw_json JSONB NOT NULL,
	raw_sha256 TEXT NOT NULL,
	segment_count INTEGER NOT NULL DEFAULT 0,
	first_seen_at TEXT NOT NULL,
	updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS transcript_segments (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	call_id TEXT NOT NULL,
	segment_index INTEGER NOT NULL,
	speaker_id TEXT NOT NULL DEFAULT '',
	start_ms BIGINT NOT NULL DEFAULT 0,
	end_ms BIGINT NOT NULL DEFAULT 0,
	text TEXT NOT NULL,
	raw_json JSONB NOT NULL,
	search_vector TSVECTOR GENERATED ALWAYS AS (to_tsvector('simple', coalesce(text, ''))) STORED,
	UNIQUE(call_id, segment_index)
);

CREATE INDEX IF NOT EXISTS idx_pg_transcript_segments_call_id ON transcript_segments(call_id, segment_index);
CREATE INDEX IF NOT EXISTS idx_pg_transcript_segments_search ON transcript_segments USING GIN(search_vector);
`,
	`
CREATE TABLE IF NOT EXISTS call_context_objects (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	call_id TEXT NOT NULL,
	object_key TEXT NOT NULL,
	object_type TEXT NOT NULL,
	object_id TEXT NOT NULL DEFAULT '',
	object_name TEXT NOT NULL DEFAULT '',
	raw_json JSONB NOT NULL,
	UNIQUE(call_id, object_key)
);

CREATE INDEX IF NOT EXISTS idx_pg_call_context_objects_call_id ON call_context_objects(call_id);
CREATE INDEX IF NOT EXISTS idx_pg_call_context_objects_type ON call_context_objects(object_type);
CREATE INDEX IF NOT EXISTS idx_pg_call_context_objects_type_object_call ON call_context_objects(object_type, object_id, call_id, object_key);
CREATE INDEX IF NOT EXISTS idx_pg_call_context_objects_type_call_key ON call_context_objects(object_type, call_id, object_key);

CREATE TABLE IF NOT EXISTS call_context_fields (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	call_id TEXT NOT NULL,
	object_key TEXT NOT NULL,
	field_name TEXT NOT NULL,
	field_label TEXT NOT NULL DEFAULT '',
	field_type TEXT NOT NULL DEFAULT '',
	field_value_text TEXT NOT NULL DEFAULT '',
	raw_json JSONB NOT NULL,
	UNIQUE(call_id, object_key, field_name)
);

CREATE INDEX IF NOT EXISTS idx_pg_call_context_fields_call_id ON call_context_fields(call_id);
CREATE INDEX IF NOT EXISTS idx_pg_call_context_fields_name ON call_context_fields(field_name);
CREATE INDEX IF NOT EXISTS idx_pg_call_context_fields_name_call_key_value ON call_context_fields(field_name, call_id, object_key, (left(field_value_text, 256)));

CREATE TABLE IF NOT EXISTS call_facts (
	call_id TEXT PRIMARY KEY,
	title TEXT NOT NULL DEFAULT '',
	started_at TEXT NOT NULL DEFAULT '',
	call_date TEXT NOT NULL DEFAULT '',
	call_month TEXT NOT NULL DEFAULT '',
	duration_seconds BIGINT NOT NULL DEFAULT 0,
	duration_bucket TEXT NOT NULL DEFAULT '',
	system TEXT NOT NULL DEFAULT '',
	direction TEXT NOT NULL DEFAULT '',
	scope TEXT NOT NULL DEFAULT 'Unknown',
	purpose TEXT NOT NULL DEFAULT '',
	primary_user_id TEXT NOT NULL DEFAULT '',
	calendar_event_present BOOLEAN NOT NULL DEFAULT false,
	calendar_event_status TEXT NOT NULL DEFAULT 'no_calendar',
	sdr_disposition TEXT NOT NULL DEFAULT '',
	transcript_present BOOLEAN NOT NULL DEFAULT false,
	transcript_status TEXT NOT NULL DEFAULT 'missing',
	lifecycle_bucket TEXT NOT NULL DEFAULT 'unknown',
	lifecycle_confidence TEXT NOT NULL DEFAULT 'low',
	lifecycle_reason TEXT NOT NULL DEFAULT '',
	lifecycle_evidence_fields TEXT NOT NULL DEFAULT '',
	account_id TEXT NOT NULL DEFAULT '',
	account_type TEXT NOT NULL DEFAULT '',
	account_industry TEXT NOT NULL DEFAULT '',
	account_revenue_range TEXT NOT NULL DEFAULT '',
	account_primary_procurement_system TEXT NOT NULL DEFAULT '',
	opportunity_id TEXT NOT NULL DEFAULT '',
	opportunity_stage TEXT NOT NULL DEFAULT '',
	opportunity_type TEXT NOT NULL DEFAULT '',
	opportunity_amount TEXT NOT NULL DEFAULT '',
	opportunity_probability TEXT NOT NULL DEFAULT '',
	opportunity_forecast_category TEXT NOT NULL DEFAULT '',
	opportunity_primary_lead_source TEXT NOT NULL DEFAULT '',
	opportunity_procurement_system TEXT NOT NULL DEFAULT '',
	opportunity_count BIGINT NOT NULL DEFAULT 0,
	account_count BIGINT NOT NULL DEFAULT 0,
	updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_pg_call_facts_lifecycle ON call_facts(lifecycle_bucket, transcript_present);
CREATE INDEX IF NOT EXISTS idx_pg_call_facts_backlog ON call_facts(transcript_present, lifecycle_bucket, call_date, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_pg_call_facts_call_date ON call_facts(call_date);
CREATE INDEX IF NOT EXISTS idx_pg_call_facts_call_month ON call_facts(call_month);
CREATE INDEX IF NOT EXISTS idx_pg_call_facts_transcript_status ON call_facts(transcript_status);
CREATE INDEX IF NOT EXISTS idx_pg_call_facts_scope_system_direction ON call_facts(scope, system, direction);
CREATE INDEX IF NOT EXISTS idx_pg_call_facts_started_at ON call_facts(started_at DESC);
CREATE INDEX IF NOT EXISTS idx_pg_call_facts_opportunity_stage ON call_facts(opportunity_stage);
CREATE INDEX IF NOT EXISTS idx_pg_call_facts_opportunity_type ON call_facts(opportunity_type);
CREATE INDEX IF NOT EXISTS idx_pg_call_facts_account_type ON call_facts(account_type);
CREATE INDEX IF NOT EXISTS idx_pg_call_facts_account_industry ON call_facts(account_industry);
`,
	`
CREATE TABLE IF NOT EXISTS postgres_read_model_state (
	model_name TEXT PRIMARY KEY,
	model_version INTEGER NOT NULL,
	rebuilt_at TEXT NOT NULL,
	call_count BIGINT NOT NULL DEFAULT 0,
	fact_count BIGINT NOT NULL DEFAULT 0,
	stale_reason TEXT NOT NULL DEFAULT '',
	updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS call_read_model_diagnostics (
	call_id TEXT PRIMARY KEY,
	object_count BIGINT NOT NULL DEFAULT 0,
	field_count BIGINT NOT NULL DEFAULT 0,
	raw_object_count BIGINT NOT NULL DEFAULT 0,
	raw_field_count BIGINT NOT NULL DEFAULT 0,
	object_limit_exceeded BOOLEAN NOT NULL DEFAULT false,
	field_limit_exceeded BOOLEAN NOT NULL DEFAULT false,
	last_error TEXT NOT NULL DEFAULT '',
	updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_pg_call_read_model_diagnostics_limits
	ON call_read_model_diagnostics(object_limit_exceeded, field_limit_exceeded, call_id);
`,
	`
CREATE INDEX IF NOT EXISTS idx_pg_calls_started_call_id
	ON calls(started_at DESC, call_id);

CREATE INDEX IF NOT EXISTS idx_pg_call_facts_search_filters
	ON call_facts(transcript_status, lifecycle_bucket, scope, system, direction, call_date, started_at DESC, call_id);
`,
	`
ALTER TABLE postgres_read_model_state
	ADD COLUMN IF NOT EXISTS missing_fact_call_count BIGINT NOT NULL DEFAULT 0,
	ADD COLUMN IF NOT EXISTS orphan_fact_count BIGINT NOT NULL DEFAULT 0;

UPDATE postgres_read_model_state
   SET call_count = (SELECT COUNT(*) FROM calls),
       fact_count = (SELECT COUNT(*) FROM call_facts),
       missing_fact_call_count = (
	       SELECT COUNT(*)
	         FROM calls c
	         LEFT JOIN call_facts cf ON cf.call_id = c.call_id
	        WHERE cf.call_id IS NULL
       ),
       orphan_fact_count = (
	       SELECT COUNT(*)
	         FROM call_facts cf
	         LEFT JOIN calls c ON c.call_id = cf.call_id
	        WHERE c.call_id IS NULL
       ),
       updated_at = to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')
 WHERE model_name = 'builtin_call_facts';

CREATE OR REPLACE FUNCTION gongctl_read_model_calls_counter_fn() RETURNS trigger AS $$
BEGIN
	IF TG_OP = 'INSERT' THEN
		UPDATE postgres_read_model_state
		   SET call_count = call_count + 1,
		       missing_fact_call_count = missing_fact_call_count + CASE WHEN EXISTS (SELECT 1 FROM call_facts WHERE call_id = NEW.call_id) THEN 0 ELSE 1 END,
		       orphan_fact_count = GREATEST(orphan_fact_count - CASE WHEN EXISTS (SELECT 1 FROM call_facts WHERE call_id = NEW.call_id) THEN 1 ELSE 0 END, 0),
		       updated_at = to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')
		 WHERE model_name = 'builtin_call_facts';
		RETURN NEW;
	ELSIF TG_OP = 'DELETE' THEN
		UPDATE postgres_read_model_state
		   SET call_count = GREATEST(call_count - 1, 0),
		       missing_fact_call_count = GREATEST(missing_fact_call_count - CASE WHEN EXISTS (SELECT 1 FROM call_facts WHERE call_id = OLD.call_id) THEN 0 ELSE 1 END, 0),
		       orphan_fact_count = orphan_fact_count + CASE WHEN EXISTS (SELECT 1 FROM call_facts WHERE call_id = OLD.call_id) THEN 1 ELSE 0 END,
		       updated_at = to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')
		 WHERE model_name = 'builtin_call_facts';
		RETURN OLD;
	END IF;
	RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION gongctl_read_model_facts_counter_fn() RETURNS trigger AS $$
BEGIN
	IF TG_OP = 'INSERT' THEN
		UPDATE postgres_read_model_state
		   SET fact_count = fact_count + 1,
		       missing_fact_call_count = GREATEST(missing_fact_call_count - CASE WHEN EXISTS (SELECT 1 FROM calls WHERE call_id = NEW.call_id) THEN 1 ELSE 0 END, 0),
		       orphan_fact_count = orphan_fact_count + CASE WHEN EXISTS (SELECT 1 FROM calls WHERE call_id = NEW.call_id) THEN 0 ELSE 1 END,
		       updated_at = to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')
		 WHERE model_name = 'builtin_call_facts';
		RETURN NEW;
	ELSIF TG_OP = 'DELETE' THEN
		UPDATE postgres_read_model_state
		   SET fact_count = GREATEST(fact_count - 1, 0),
		       missing_fact_call_count = missing_fact_call_count + CASE WHEN EXISTS (SELECT 1 FROM calls WHERE call_id = OLD.call_id) THEN 1 ELSE 0 END,
		       orphan_fact_count = GREATEST(orphan_fact_count - CASE WHEN EXISTS (SELECT 1 FROM calls WHERE call_id = OLD.call_id) THEN 0 ELSE 1 END, 0),
		       updated_at = to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')
		 WHERE model_name = 'builtin_call_facts';
		RETURN OLD;
	END IF;
	RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION gongctl_read_model_recalculate_counters_fn() RETURNS trigger AS $$
BEGIN
	UPDATE postgres_read_model_state
	   SET call_count = (SELECT COUNT(*) FROM calls),
	       fact_count = (SELECT COUNT(*) FROM call_facts),
	       missing_fact_call_count = (
		       SELECT COUNT(*)
		         FROM calls c
		         LEFT JOIN call_facts cf ON cf.call_id = c.call_id
		        WHERE cf.call_id IS NULL
	       ),
	       orphan_fact_count = (
		       SELECT COUNT(*)
		         FROM call_facts cf
		         LEFT JOIN calls c ON c.call_id = cf.call_id
		        WHERE c.call_id IS NULL
	       ),
	       updated_at = to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')
	 WHERE model_name = 'builtin_call_facts';
	RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS gongctl_read_model_calls_counter ON calls;
CREATE TRIGGER gongctl_read_model_calls_counter
AFTER INSERT OR DELETE ON calls
FOR EACH ROW EXECUTE FUNCTION gongctl_read_model_calls_counter_fn();

DROP TRIGGER IF EXISTS gongctl_read_model_calls_update_resync ON calls;
CREATE TRIGGER gongctl_read_model_calls_update_resync
AFTER UPDATE OF call_id ON calls
FOR EACH STATEMENT EXECUTE FUNCTION gongctl_read_model_recalculate_counters_fn();

DROP TRIGGER IF EXISTS gongctl_read_model_calls_truncate_resync ON calls;
CREATE TRIGGER gongctl_read_model_calls_truncate_resync
AFTER TRUNCATE ON calls
FOR EACH STATEMENT EXECUTE FUNCTION gongctl_read_model_recalculate_counters_fn();

DROP TRIGGER IF EXISTS gongctl_read_model_facts_counter ON call_facts;
CREATE TRIGGER gongctl_read_model_facts_counter
AFTER INSERT OR DELETE ON call_facts
FOR EACH ROW EXECUTE FUNCTION gongctl_read_model_facts_counter_fn();

DROP TRIGGER IF EXISTS gongctl_read_model_facts_update_resync ON call_facts;
CREATE TRIGGER gongctl_read_model_facts_update_resync
AFTER UPDATE OF call_id ON call_facts
FOR EACH STATEMENT EXECUTE FUNCTION gongctl_read_model_recalculate_counters_fn();

DROP TRIGGER IF EXISTS gongctl_read_model_facts_truncate_resync ON call_facts;
CREATE TRIGGER gongctl_read_model_facts_truncate_resync
AFTER TRUNCATE ON call_facts
FOR EACH STATEMENT EXECUTE FUNCTION gongctl_read_model_recalculate_counters_fn();
`,
}
