package postgres

var migrations = []string{
	`
CREATE TABLE IF NOT EXISTS gongctl_schema_migrations (
	version INTEGER PRIMARY KEY,
	applied_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sync_runs (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	scope TEXT NOT NULL,
	sync_key TEXT NOT NULL DEFAULT '',
	cursor TEXT NOT NULL DEFAULT '',
	from_value TEXT NOT NULL DEFAULT '',
	to_value TEXT NOT NULL DEFAULT '',
	request_context TEXT NOT NULL DEFAULT '',
	status TEXT NOT NULL,
	started_at TEXT NOT NULL,
	finished_at TEXT,
	records_seen BIGINT NOT NULL DEFAULT 0,
	records_written BIGINT NOT NULL DEFAULT 0,
	error_text TEXT NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_pg_sync_runs_scope_started_at ON sync_runs(scope, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_pg_sync_runs_status ON sync_runs(status);

CREATE TABLE IF NOT EXISTS sync_state (
	sync_key TEXT PRIMARY KEY,
	scope TEXT NOT NULL,
	cursor TEXT NOT NULL DEFAULT '',
	last_run_id BIGINT,
	last_status TEXT NOT NULL,
	last_error TEXT NOT NULL DEFAULT '',
	last_success_at TEXT,
	updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_pg_sync_state_scope ON sync_state(scope);

CREATE TABLE IF NOT EXISTS calls (
	call_id TEXT PRIMARY KEY,
	title TEXT NOT NULL DEFAULT '',
	started_at TEXT NOT NULL DEFAULT '',
	duration_seconds BIGINT NOT NULL DEFAULT 0,
	parties_count BIGINT NOT NULL DEFAULT 0,
	context_present BOOLEAN NOT NULL DEFAULT false,
	raw_json JSONB NOT NULL,
	raw_sha256 TEXT NOT NULL,
	first_seen_at TEXT NOT NULL,
	updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_pg_calls_started_at ON calls(started_at DESC);

CREATE TABLE IF NOT EXISTS users (
	user_id TEXT PRIMARY KEY,
	email TEXT NOT NULL DEFAULT '',
	first_name TEXT NOT NULL DEFAULT '',
	last_name TEXT NOT NULL DEFAULT '',
	display_name TEXT NOT NULL DEFAULT '',
	title TEXT NOT NULL DEFAULT '',
	active BOOLEAN NOT NULL DEFAULT false,
	raw_json JSONB NOT NULL,
	raw_sha256 TEXT NOT NULL,
	first_seen_at TEXT NOT NULL,
	updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_pg_users_email ON users(email);

CREATE TABLE IF NOT EXISTS transcripts (
	call_id TEXT PRIMARY KEY,
	raw_json JSONB NOT NULL,
	raw_sha256 TEXT NOT NULL,
	segment_count INTEGER NOT NULL DEFAULT 0,
	first_seen_at TEXT NOT NULL,
	updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS transcript_segments (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	call_id TEXT NOT NULL,
	segment_index INTEGER NOT NULL,
	speaker_id TEXT NOT NULL DEFAULT '',
	start_ms BIGINT NOT NULL DEFAULT 0,
	end_ms BIGINT NOT NULL DEFAULT 0,
	text TEXT NOT NULL,
	raw_json JSONB NOT NULL,
	search_vector TSVECTOR GENERATED ALWAYS AS (to_tsvector('simple', coalesce(text, ''))) STORED,
	UNIQUE(call_id, segment_index)
);

CREATE INDEX IF NOT EXISTS idx_pg_transcript_segments_call_id ON transcript_segments(call_id, segment_index);
CREATE INDEX IF NOT EXISTS idx_pg_transcript_segments_search ON transcript_segments USING GIN(search_vector);
`,
	`
CREATE TABLE IF NOT EXISTS call_context_objects (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	call_id TEXT NOT NULL,
	object_key TEXT NOT NULL,
	object_type TEXT NOT NULL,
	object_id TEXT NOT NULL DEFAULT '',
	object_name TEXT NOT NULL DEFAULT '',
	raw_json JSONB NOT NULL,
	UNIQUE(call_id, object_key)
);

CREATE INDEX IF NOT EXISTS idx_pg_call_context_objects_call_id ON call_context_objects(call_id);
CREATE INDEX IF NOT EXISTS idx_pg_call_context_objects_type ON call_context_objects(object_type);
CREATE INDEX IF NOT EXISTS idx_pg_call_context_objects_type_object_call ON call_context_objects(object_type, object_id, call_id, object_key);
CREATE INDEX IF NOT EXISTS idx_pg_call_context_objects_type_call_key ON call_context_objects(object_type, call_id, object_key);

CREATE TABLE IF NOT EXISTS call_context_fields (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	call_id TEXT NOT NULL,
	object_key TEXT NOT NULL,
	field_name TEXT NOT NULL,
	field_label TEXT NOT NULL DEFAULT '',
	field_type TEXT NOT NULL DEFAULT '',
	field_value_text TEXT NOT NULL DEFAULT '',
	raw_json JSONB NOT NULL,
	UNIQUE(call_id, object_key, field_name)
);

CREATE INDEX IF NOT EXISTS idx_pg_call_context_fields_call_id ON call_context_fields(call_id);
CREATE INDEX IF NOT EXISTS idx_pg_call_context_fields_name ON call_context_fields(field_name);
CREATE INDEX IF NOT EXISTS idx_pg_call_context_fields_name_call_key_value ON call_context_fields(field_name, call_id, object_key, (left(field_value_text, 256)));

CREATE TABLE IF NOT EXISTS call_facts (
	call_id TEXT PRIMARY KEY,
	title TEXT NOT NULL DEFAULT '',
	started_at TEXT NOT NULL DEFAULT '',
	call_date TEXT NOT NULL DEFAULT '',
	call_month TEXT NOT NULL DEFAULT '',
	duration_seconds BIGINT NOT NULL DEFAULT 0,
	duration_bucket TEXT NOT NULL DEFAULT '',
	system TEXT NOT NULL DEFAULT '',
	direction TEXT NOT NULL DEFAULT '',
	scope TEXT NOT NULL DEFAULT 'Unknown',
	purpose TEXT NOT NULL DEFAULT '',
	primary_user_id TEXT NOT NULL DEFAULT '',
	calendar_event_present BOOLEAN NOT NULL DEFAULT false,
	calendar_event_status TEXT NOT NULL DEFAULT 'no_calendar',
	sdr_disposition TEXT NOT NULL DEFAULT '',
	transcript_present BOOLEAN NOT NULL DEFAULT false,
	transcript_status TEXT NOT NULL DEFAULT 'missing',
	lifecycle_bucket TEXT NOT NULL DEFAULT 'unknown',
	lifecycle_confidence TEXT NOT NULL DEFAULT 'low',
	lifecycle_reason TEXT NOT NULL DEFAULT '',
	lifecycle_evidence_fields TEXT NOT NULL DEFAULT '',
	account_id TEXT NOT NULL DEFAULT '',
	account_type TEXT NOT NULL DEFAULT '',
	account_industry TEXT NOT NULL DEFAULT '',
	account_revenue_range TEXT NOT NULL DEFAULT '',
	account_primary_procurement_system TEXT NOT NULL DEFAULT '',
	opportunity_id TEXT NOT NULL DEFAULT '',
	opportunity_stage TEXT NOT NULL DEFAULT '',
	opportunity_type TEXT NOT NULL DEFAULT '',
	opportunity_amount TEXT NOT NULL DEFAULT '',
	opportunity_probability TEXT NOT NULL DEFAULT '',
	opportunity_forecast_category TEXT NOT NULL DEFAULT '',
	opportunity_primary_lead_source TEXT NOT NULL DEFAULT '',
	opportunity_procurement_system TEXT NOT NULL DEFAULT '',
	opportunity_count BIGINT NOT NULL DEFAULT 0,
	account_count BIGINT NOT NULL DEFAULT 0,
	participant_title_present BOOLEAN NOT NULL DEFAULT false,
	loss_reason_present BOOLEAN NOT NULL DEFAULT false,
	updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_pg_call_facts_lifecycle ON call_facts(lifecycle_bucket, transcript_present);
CREATE INDEX IF NOT EXISTS idx_pg_call_facts_backlog ON call_facts(transcript_present, lifecycle_bucket, call_date, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_pg_call_facts_call_date ON call_facts(call_date);
CREATE INDEX IF NOT EXISTS idx_pg_call_facts_call_month ON call_facts(call_month);
CREATE INDEX IF NOT EXISTS idx_pg_call_facts_transcript_status ON call_facts(transcript_status);
CREATE INDEX IF NOT EXISTS idx_pg_call_facts_scope_system_direction ON call_facts(scope, system, direction);
CREATE INDEX IF NOT EXISTS idx_pg_call_facts_started_at ON call_facts(started_at DESC);
CREATE INDEX IF NOT EXISTS idx_pg_call_facts_opportunity_stage ON call_facts(opportunity_stage);
CREATE INDEX IF NOT EXISTS idx_pg_call_facts_opportunity_type ON call_facts(opportunity_type);
CREATE INDEX IF NOT EXISTS idx_pg_call_facts_account_type ON call_facts(account_type);
CREATE INDEX IF NOT EXISTS idx_pg_call_facts_account_industry ON call_facts(account_industry);
CREATE INDEX IF NOT EXISTS idx_pg_call_facts_participant_title_present ON call_facts(participant_title_present, call_date, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_pg_call_facts_loss_reason_present ON call_facts(loss_reason_present, call_date, started_at DESC);
`,
	`
CREATE TABLE IF NOT EXISTS postgres_read_model_state (
	model_name TEXT PRIMARY KEY,
	model_version INTEGER NOT NULL,
	rebuilt_at TEXT NOT NULL,
	call_count BIGINT NOT NULL DEFAULT 0,
	fact_count BIGINT NOT NULL DEFAULT 0,
	stale_reason TEXT NOT NULL DEFAULT '',
	updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS call_read_model_diagnostics (
	call_id TEXT PRIMARY KEY,
	object_count BIGINT NOT NULL DEFAULT 0,
	field_count BIGINT NOT NULL DEFAULT 0,
	raw_object_count BIGINT NOT NULL DEFAULT 0,
	raw_field_count BIGINT NOT NULL DEFAULT 0,
	object_limit_exceeded BOOLEAN NOT NULL DEFAULT false,
	field_limit_exceeded BOOLEAN NOT NULL DEFAULT false,
	last_error TEXT NOT NULL DEFAULT '',
	updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_pg_call_read_model_diagnostics_limits
	ON call_read_model_diagnostics(object_limit_exceeded, field_limit_exceeded, call_id);
`,
	`
CREATE INDEX IF NOT EXISTS idx_pg_calls_started_call_id
	ON calls(started_at DESC, call_id);

CREATE INDEX IF NOT EXISTS idx_pg_call_facts_search_filters
	ON call_facts(transcript_status, lifecycle_bucket, scope, system, direction, call_date, started_at DESC, call_id);
`,
	`
ALTER TABLE postgres_read_model_state
	ADD COLUMN IF NOT EXISTS missing_fact_call_count BIGINT NOT NULL DEFAULT 0,
	ADD COLUMN IF NOT EXISTS orphan_fact_count BIGINT NOT NULL DEFAULT 0;

UPDATE postgres_read_model_state
   SET call_count = (SELECT COUNT(*) FROM calls),
       fact_count = (SELECT COUNT(*) FROM call_facts),
       missing_fact_call_count = (
	       SELECT COUNT(*)
	         FROM calls c
	         LEFT JOIN call_facts cf ON cf.call_id = c.call_id
	        WHERE cf.call_id IS NULL
       ),
       orphan_fact_count = (
	       SELECT COUNT(*)
	         FROM call_facts cf
	         LEFT JOIN calls c ON c.call_id = cf.call_id
	        WHERE c.call_id IS NULL
       ),
       updated_at = to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')
 WHERE model_name = 'builtin_call_facts';

CREATE OR REPLACE FUNCTION gongctl_read_model_calls_counter_fn() RETURNS trigger AS $$
BEGIN
	IF TG_OP = 'INSERT' THEN
		UPDATE postgres_read_model_state
		   SET call_count = call_count + 1,
		       missing_fact_call_count = missing_fact_call_count + CASE WHEN EXISTS (SELECT 1 FROM call_facts WHERE call_id = NEW.call_id) THEN 0 ELSE 1 END,
		       orphan_fact_count = GREATEST(orphan_fact_count - CASE WHEN EXISTS (SELECT 1 FROM call_facts WHERE call_id = NEW.call_id) THEN 1 ELSE 0 END, 0),
		       updated_at = to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')
		 WHERE model_name = 'builtin_call_facts';
		RETURN NEW;
	ELSIF TG_OP = 'DELETE' THEN
		UPDATE postgres_read_model_state
		   SET call_count = GREATEST(call_count - 1, 0),
		       missing_fact_call_count = GREATEST(missing_fact_call_count - CASE WHEN EXISTS (SELECT 1 FROM call_facts WHERE call_id = OLD.call_id) THEN 0 ELSE 1 END, 0),
		       orphan_fact_count = orphan_fact_count + CASE WHEN EXISTS (SELECT 1 FROM call_facts WHERE call_id = OLD.call_id) THEN 1 ELSE 0 END,
		       updated_at = to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')
		 WHERE model_name = 'builtin_call_facts';
		RETURN OLD;
	END IF;
	RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION gongctl_read_model_facts_counter_fn() RETURNS trigger AS $$
BEGIN
	IF TG_OP = 'INSERT' THEN
		UPDATE postgres_read_model_state
		   SET fact_count = fact_count + 1,
		       missing_fact_call_count = GREATEST(missing_fact_call_count - CASE WHEN EXISTS (SELECT 1 FROM calls WHERE call_id = NEW.call_id) THEN 1 ELSE 0 END, 0),
		       orphan_fact_count = orphan_fact_count + CASE WHEN EXISTS (SELECT 1 FROM calls WHERE call_id = NEW.call_id) THEN 0 ELSE 1 END,
		       updated_at = to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')
		 WHERE model_name = 'builtin_call_facts';
		RETURN NEW;
	ELSIF TG_OP = 'DELETE' THEN
		UPDATE postgres_read_model_state
		   SET fact_count = GREATEST(fact_count - 1, 0),
		       missing_fact_call_count = missing_fact_call_count + CASE WHEN EXISTS (SELECT 1 FROM calls WHERE call_id = OLD.call_id) THEN 1 ELSE 0 END,
		       orphan_fact_count = GREATEST(orphan_fact_count - CASE WHEN EXISTS (SELECT 1 FROM calls WHERE call_id = OLD.call_id) THEN 0 ELSE 1 END, 0),
		       updated_at = to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')
		 WHERE model_name = 'builtin_call_facts';
		RETURN OLD;
	END IF;
	RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION gongctl_read_model_recalculate_counters_fn() RETURNS trigger AS $$
BEGIN
	UPDATE postgres_read_model_state
	   SET call_count = (SELECT COUNT(*) FROM calls),
	       fact_count = (SELECT COUNT(*) FROM call_facts),
	       missing_fact_call_count = (
		       SELECT COUNT(*)
		         FROM calls c
		         LEFT JOIN call_facts cf ON cf.call_id = c.call_id
		        WHERE cf.call_id IS NULL
	       ),
	       orphan_fact_count = (
		       SELECT COUNT(*)
		         FROM call_facts cf
		         LEFT JOIN calls c ON c.call_id = cf.call_id
		        WHERE c.call_id IS NULL
	       ),
	       updated_at = to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')
	 WHERE model_name = 'builtin_call_facts';
	RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS gongctl_read_model_calls_counter ON calls;
CREATE TRIGGER gongctl_read_model_calls_counter
AFTER INSERT OR DELETE ON calls
FOR EACH ROW EXECUTE FUNCTION gongctl_read_model_calls_counter_fn();

DROP TRIGGER IF EXISTS gongctl_read_model_calls_update_resync ON calls;
CREATE TRIGGER gongctl_read_model_calls_update_resync
AFTER UPDATE OF call_id ON calls
FOR EACH STATEMENT EXECUTE FUNCTION gongctl_read_model_recalculate_counters_fn();

DROP TRIGGER IF EXISTS gongctl_read_model_calls_truncate_resync ON calls;
CREATE TRIGGER gongctl_read_model_calls_truncate_resync
AFTER TRUNCATE ON calls
FOR EACH STATEMENT EXECUTE FUNCTION gongctl_read_model_recalculate_counters_fn();

DROP TRIGGER IF EXISTS gongctl_read_model_facts_counter ON call_facts;
CREATE TRIGGER gongctl_read_model_facts_counter
AFTER INSERT OR DELETE ON call_facts
FOR EACH ROW EXECUTE FUNCTION gongctl_read_model_facts_counter_fn();

DROP TRIGGER IF EXISTS gongctl_read_model_facts_update_resync ON call_facts;
CREATE TRIGGER gongctl_read_model_facts_update_resync
AFTER UPDATE OF call_id ON call_facts
FOR EACH STATEMENT EXECUTE FUNCTION gongctl_read_model_recalculate_counters_fn();

DROP TRIGGER IF EXISTS gongctl_read_model_facts_truncate_resync ON call_facts;
CREATE TRIGGER gongctl_read_model_facts_truncate_resync
AFTER TRUNCATE ON call_facts
FOR EACH STATEMENT EXECUTE FUNCTION gongctl_read_model_recalculate_counters_fn();
	`,
	`
CREATE OR REPLACE VIEW gongmcp_sync_runs AS SELECT id, scope, sync_key, ''::text AS cursor, from_value, to_value, ''::text AS request_context, status, started_at, finished_at, records_seen, records_written, ''::text AS error_text FROM sync_runs;
CREATE OR REPLACE VIEW gongmcp_sync_state AS SELECT sync_key, scope, ''::text AS cursor, last_run_id, last_status, ''::text AS last_error, last_success_at, updated_at FROM sync_state;
CREATE OR REPLACE VIEW gongmcp_call_context_objects AS SELECT id, call_id, 'object:' || id::text AS object_key, object_type FROM call_context_objects;
CREATE OR REPLACE VIEW gongmcp_call_context_fields AS SELECT f.id, f.call_id, 'object:' || o.id::text AS object_key, f.field_name, f.field_label, f.field_type, (TRIM(f.field_value_text) <> '') AS field_populated FROM call_context_fields f JOIN call_context_objects o ON o.call_id = f.call_id AND o.object_key = f.object_key;
DROP VIEW IF EXISTS gongmcp_transcript_segments;
CREATE OR REPLACE FUNCTION gongmcp_search_transcript_segments(search_text text, row_limit integer)
RETURNS TABLE(call_id text, speaker_id text, segment_index integer, start_ms bigint, end_ms bigint, text text, snippet text)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $function$
WITH q AS (
	SELECT websearch_to_tsquery('simple', search_text) AS query
),
bounded AS (
	SELECT LEAST(GREATEST(COALESCE(row_limit, 20), 1), 1000) AS limit_value
)
SELECT ts.call_id,
       ts.speaker_id,
       ts.segment_index,
       ts.start_ms,
       ts.end_ms,
       ''::text AS text,
       ts_headline('simple', ts.text, q.query, 'StartSel=[, StopSel=], MaxWords=12, MinWords=4, ShortWord=2') AS snippet
  FROM transcript_segments ts, q, bounded
 WHERE ts.search_vector @@ q.query
 ORDER BY ts_rank_cd(ts.search_vector, q.query) DESC, ts.call_id, ts.segment_index
 LIMIT (SELECT limit_value FROM bounded)
$function$;
REVOKE ALL ON FUNCTION gongmcp_search_transcript_segments(text, integer) FROM PUBLIC;

DO $$
BEGIN
	IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'gongmcp_reader') THEN
		EXECUTE 'REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM gongmcp_reader';
		EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE SELECT ON TABLES FROM gongmcp_reader';
		EXECUTE 'GRANT CONNECT ON DATABASE ' || quote_ident(current_database()) || ' TO gongmcp_reader';
		EXECUTE 'GRANT USAGE ON SCHEMA public TO gongmcp_reader';
		EXECUTE 'GRANT SELECT ON TABLE gongctl_schema_migrations TO gongmcp_reader';
		EXECUTE 'GRANT SELECT ON TABLE gongmcp_sync_runs TO gongmcp_reader';
		EXECUTE 'GRANT SELECT ON TABLE gongmcp_sync_state TO gongmcp_reader';
		EXECUTE 'GRANT SELECT (call_id, title, started_at, duration_seconds, parties_count, context_present, first_seen_at, updated_at) ON calls TO gongmcp_reader';
		EXECUTE 'GRANT SELECT (user_id, title, active, first_seen_at, updated_at) ON users TO gongmcp_reader';
		EXECUTE 'GRANT SELECT (call_id, segment_count, first_seen_at, updated_at) ON transcripts TO gongmcp_reader';
		EXECUTE 'GRANT EXECUTE ON FUNCTION gongmcp_search_transcript_segments(text, integer) TO gongmcp_reader';
		EXECUTE 'GRANT SELECT (id, call_id, object_type) ON call_context_objects TO gongmcp_reader';
		EXECUTE 'GRANT SELECT ON TABLE gongmcp_call_context_objects TO gongmcp_reader';
		EXECUTE 'GRANT SELECT ON TABLE gongmcp_call_context_fields TO gongmcp_reader';
		EXECUTE 'GRANT SELECT (call_id, title, started_at, call_date, call_month, duration_seconds, duration_bucket, system, direction, scope, purpose, calendar_event_present, transcript_present, transcript_status, lifecycle_bucket, lifecycle_confidence, lifecycle_reason, lifecycle_evidence_fields, account_type, account_industry, account_revenue_range, opportunity_stage, opportunity_type, opportunity_forecast_category, opportunity_primary_lead_source, opportunity_count, account_count) ON call_facts TO gongmcp_reader';
		EXECUTE 'GRANT SELECT ON TABLE postgres_read_model_state TO gongmcp_reader';
		EXECUTE 'GRANT SELECT ON TABLE call_read_model_diagnostics TO gongmcp_reader';
	END IF;
END;
$$;
`,
	`
CREATE TABLE IF NOT EXISTS profile_meta (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name TEXT NOT NULL DEFAULT '',
	version INTEGER NOT NULL,
	source_path TEXT NOT NULL DEFAULT '',
	source_sha256 TEXT NOT NULL,
	canonical_sha256 TEXT NOT NULL,
	imported_at TEXT NOT NULL,
	imported_by TEXT NOT NULL DEFAULT '',
	is_active BOOLEAN NOT NULL DEFAULT false,
	raw_yaml BYTEA NOT NULL,
	canonical_json JSONB NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_pg_profile_meta_canonical_sha
	ON profile_meta(canonical_sha256);

CREATE INDEX IF NOT EXISTS idx_pg_profile_meta_active
	ON profile_meta(is_active);

CREATE TABLE IF NOT EXISTS profile_object_alias (
	profile_id BIGINT NOT NULL,
	concept TEXT NOT NULL,
	object_type TEXT NOT NULL,
	PRIMARY KEY(profile_id, concept, object_type)
);

CREATE TABLE IF NOT EXISTS profile_field_concept (
	profile_id BIGINT NOT NULL,
	concept TEXT NOT NULL,
	object_concept TEXT NOT NULL,
	field_name TEXT NOT NULL,
	confidence DOUBLE PRECISION NOT NULL DEFAULT 0,
	evidence_json JSONB NOT NULL DEFAULT '{}'::jsonb,
	PRIMARY KEY(profile_id, concept, object_concept, field_name)
);

CREATE TABLE IF NOT EXISTS profile_lifecycle_rule (
	profile_id BIGINT NOT NULL,
	bucket TEXT NOT NULL,
	ordinal INTEGER NOT NULL DEFAULT 0,
	label TEXT NOT NULL DEFAULT '',
	description TEXT NOT NULL DEFAULT '',
	rule_index INTEGER NOT NULL DEFAULT 0,
	rule_json JSONB NOT NULL DEFAULT '{}'::jsonb,
	PRIMARY KEY(profile_id, bucket, rule_index)
);

CREATE TABLE IF NOT EXISTS profile_methodology_concept (
	profile_id BIGINT NOT NULL,
	concept TEXT NOT NULL,
	description TEXT NOT NULL DEFAULT '',
	aliases_json JSONB NOT NULL DEFAULT '[]'::jsonb,
	fields_json JSONB NOT NULL DEFAULT '[]'::jsonb,
	tracker_ids_json JSONB NOT NULL DEFAULT '[]'::jsonb,
	scorecard_question_ids_json JSONB NOT NULL DEFAULT '[]'::jsonb,
	PRIMARY KEY(profile_id, concept)
);

CREATE TABLE IF NOT EXISTS profile_validation_warning (
	profile_id BIGINT NOT NULL,
	severity TEXT NOT NULL,
	code TEXT NOT NULL,
	message TEXT NOT NULL,
	path TEXT NOT NULL DEFAULT ''
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_pg_profile_validation_warning_unique
	ON profile_validation_warning(profile_id, severity, code, path);

CREATE INDEX IF NOT EXISTS idx_pg_profile_validation_warning_profile
	ON profile_validation_warning(profile_id, severity);

CREATE TABLE IF NOT EXISTS profile_call_fact_cache_meta (
	profile_id BIGINT PRIMARY KEY,
	canonical_sha256 TEXT NOT NULL,
	data_fingerprint TEXT NOT NULL,
	built_at TEXT NOT NULL,
	call_count BIGINT NOT NULL DEFAULT 0
);

`,
	`
CREATE TABLE IF NOT EXISTS profile_call_fact_cache (
	profile_id BIGINT NOT NULL,
	canonical_sha256 TEXT NOT NULL,
	call_id TEXT NOT NULL,
	title TEXT NOT NULL DEFAULT '',
	started_at TEXT NOT NULL DEFAULT '',
	duration_seconds BIGINT NOT NULL DEFAULT 0,
	system TEXT NOT NULL DEFAULT '',
	direction TEXT NOT NULL DEFAULT '',
	scope TEXT NOT NULL DEFAULT '',
	purpose TEXT NOT NULL DEFAULT '',
	calendar_event_present BOOLEAN NOT NULL DEFAULT false,
	transcript_present BOOLEAN NOT NULL DEFAULT false,
	lifecycle_bucket TEXT NOT NULL DEFAULT 'unknown',
	lifecycle_confidence TEXT NOT NULL DEFAULT 'low',
	lifecycle_reason TEXT NOT NULL DEFAULT '',
	evidence_fields_json JSONB NOT NULL DEFAULT '[]'::jsonb,
	deal_count BIGINT NOT NULL DEFAULT 0,
	account_count BIGINT NOT NULL DEFAULT 0,
	field_values_json JSONB NOT NULL DEFAULT '{}'::jsonb,
	PRIMARY KEY(profile_id, canonical_sha256, call_id)
);

CREATE INDEX IF NOT EXISTS idx_pg_profile_call_fact_cache_bucket
	ON profile_call_fact_cache(profile_id, canonical_sha256, lifecycle_bucket, transcript_present);

CREATE INDEX IF NOT EXISTS idx_pg_profile_call_fact_cache_started
	ON profile_call_fact_cache(profile_id, canonical_sha256, started_at DESC);

CREATE INDEX IF NOT EXISTS idx_pg_profile_call_fact_cache_backlog
	ON profile_call_fact_cache(profile_id, canonical_sha256, lifecycle_bucket, scope, system, direction, started_at DESC)
	WHERE transcript_present = false;

CREATE INDEX IF NOT EXISTS idx_pg_profile_call_fact_cache_call
	ON profile_call_fact_cache(call_id);

DROP FUNCTION IF EXISTS gongmcp_profile_call_fact_cache_meta(bigint, text);
CREATE OR REPLACE FUNCTION gongmcp_profile_call_fact_cache_meta(profile_id_arg bigint, canonical_sha_arg text)
RETURNS TABLE(canonical_sha256 text, data_fingerprint text, built_at text, call_count bigint)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $function$
SELECT m.canonical_sha256, m.data_fingerprint, m.built_at, m.call_count
  FROM profile_call_fact_cache_meta m
  JOIN profile_meta p
    ON p.id = m.profile_id
 WHERE p.is_active = true
   AND m.profile_id = profile_id_arg
   AND (canonical_sha_arg = '' OR m.canonical_sha256 = canonical_sha_arg)
$function$;

REVOKE ALL ON FUNCTION gongmcp_profile_call_fact_cache_meta(bigint, text) FROM PUBLIC;

DROP FUNCTION IF EXISTS gongmcp_profile_call_fact_cache_meta_sanitized(bigint);
CREATE OR REPLACE FUNCTION gongmcp_profile_call_fact_cache_meta_sanitized(profile_id_arg bigint)
RETURNS TABLE(data_fingerprint text, built_at text, call_count bigint)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $function$
SELECT m.data_fingerprint, m.built_at, m.call_count
  FROM profile_call_fact_cache_meta m
  JOIN profile_meta p
    ON p.id = m.profile_id
 WHERE p.is_active = true
   AND m.profile_id = profile_id_arg
 ORDER BY m.built_at DESC, m.canonical_sha256 DESC
 LIMIT 1
$function$;

REVOKE ALL ON FUNCTION gongmcp_profile_call_fact_cache_meta_sanitized(bigint) FROM PUBLIC;

DROP FUNCTION IF EXISTS gongmcp_profile_data_fingerprint();
CREATE OR REPLACE FUNCTION gongmcp_profile_data_fingerprint()
RETURNS TABLE(fingerprint text)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $function$
SELECT 'calls:' || (SELECT COUNT(*) FROM calls)::text || ':' || COALESCE((SELECT MAX(updated_at) FROM calls), '') ||
       '|objects:' || (SELECT COUNT(*) FROM call_context_objects)::text || ':' || COALESCE((SELECT md5(COALESCE(string_agg(call_id || E'\x1f' || object_key || E'\x1f' || object_type || E'\x1f' || object_id || E'\x1f' || object_name, E'\x1e' ORDER BY call_id, object_key), '')) FROM call_context_objects), '') ||
       '|fields:' || (SELECT COUNT(*) FROM call_context_fields)::text || ':' || COALESCE((SELECT md5(COALESCE(string_agg(call_id || E'\x1f' || object_key || E'\x1f' || field_name || E'\x1f' || field_label || E'\x1f' || field_type || E'\x1f' || field_value_text, E'\x1e' ORDER BY call_id, object_key, field_name), '')) FROM call_context_fields), '') ||
       '|transcripts:' || (SELECT COUNT(*) FROM transcripts)::text || ':' || COALESCE((SELECT MAX(updated_at) FROM transcripts), '') AS fingerprint
$function$;

REVOKE ALL ON FUNCTION gongmcp_profile_data_fingerprint() FROM PUBLIC;

DROP FUNCTION IF EXISTS gongmcp_profile_call_fact_cache(bigint, text);
CREATE OR REPLACE FUNCTION gongmcp_profile_call_fact_cache(profile_id_arg bigint, canonical_sha_arg text)
RETURNS TABLE(
	call_id text,
	title text,
	started_at text,
	duration_seconds bigint,
	system text,
	direction text,
	scope text,
	purpose text,
	calendar_event_present boolean,
	transcript_present boolean,
	lifecycle_bucket text,
	lifecycle_confidence text,
	lifecycle_reason text,
	evidence_fields_json jsonb,
	deal_count bigint,
	account_count bigint
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $function$
SELECT c.call_id,
       c.title,
       c.started_at,
       c.duration_seconds,
       c.system,
       c.direction,
       c.scope,
       c.purpose,
       c.calendar_event_present,
       c.transcript_present,
       c.lifecycle_bucket,
       c.lifecycle_confidence,
       c.lifecycle_reason,
       c.evidence_fields_json,
       c.deal_count,
       c.account_count
  FROM profile_call_fact_cache c
  JOIN profile_meta p
    ON p.id = c.profile_id
 WHERE p.is_active = true
   AND c.profile_id = profile_id_arg
   AND (canonical_sha_arg = '' OR c.canonical_sha256 = canonical_sha_arg)
$function$;

REVOKE ALL ON FUNCTION gongmcp_profile_call_fact_cache(bigint, text) FROM PUBLIC;

DROP FUNCTION IF EXISTS gongmcp_profile_call_fact_cache_sanitized(bigint, text);
CREATE OR REPLACE FUNCTION gongmcp_profile_call_fact_cache_sanitized(profile_id_arg bigint, canonical_sha_arg text)
RETURNS TABLE(
	call_id text,
	title text,
	started_at text,
	duration_seconds bigint,
	system text,
	direction text,
	scope text,
	purpose text,
	calendar_event_present boolean,
	transcript_present boolean,
	lifecycle_bucket text,
	lifecycle_confidence text,
	lifecycle_reason text,
	evidence_fields_json jsonb,
	deal_count bigint,
	account_count bigint
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $function$
SELECT ''::text AS call_id,
       ''::text AS title,
       c.started_at,
       c.duration_seconds,
       c.system,
       c.direction,
       c.scope,
       c.purpose,
       c.calendar_event_present,
       c.transcript_present,
       c.lifecycle_bucket,
       c.lifecycle_confidence,
       c.lifecycle_reason,
       c.evidence_fields_json,
       c.deal_count,
       c.account_count
  FROM profile_call_fact_cache c
  JOIN profile_meta p
    ON p.id = c.profile_id
 WHERE p.is_active = true
   AND c.profile_id = profile_id_arg
   AND (canonical_sha_arg = '' OR c.canonical_sha256 = canonical_sha_arg)
$function$;
REVOKE ALL ON FUNCTION gongmcp_profile_call_fact_cache_sanitized(bigint, text) FROM PUBLIC;

DROP FUNCTION IF EXISTS gongmcp_profile_call_fact_cache_sanitized_limited(bigint, text, integer);
CREATE OR REPLACE FUNCTION gongmcp_profile_call_fact_cache_sanitized_limited(profile_id_arg bigint, canonical_sha_arg text, row_limit integer)
RETURNS TABLE(
	call_id text,
	title text,
	started_at text,
	duration_seconds bigint,
	system text,
	direction text,
	scope text,
	purpose text,
	calendar_event_present boolean,
	transcript_present boolean,
	lifecycle_bucket text,
	lifecycle_confidence text,
	lifecycle_reason text,
	evidence_fields_json jsonb,
	deal_count bigint,
	account_count bigint
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $function$
SELECT ''::text AS call_id,
       ''::text AS title,
       c.started_at,
       c.duration_seconds,
       c.system,
       c.direction,
       c.scope,
       c.purpose,
       c.calendar_event_present,
       c.transcript_present,
       c.lifecycle_bucket,
       c.lifecycle_confidence,
       c.lifecycle_reason,
       c.evidence_fields_json,
       c.deal_count,
       c.account_count
  FROM profile_call_fact_cache c
  JOIN profile_meta p
    ON p.id = c.profile_id
 WHERE p.is_active = true
   AND c.profile_id = profile_id_arg
   AND (canonical_sha_arg = '' OR c.canonical_sha256 = canonical_sha_arg)
 ORDER BY c.started_at DESC, c.call_id
 LIMIT LEAST(GREATEST(COALESCE(row_limit, 1000), 1), 1000)
$function$;
REVOKE ALL ON FUNCTION gongmcp_profile_call_fact_cache_sanitized_limited(bigint, text, integer) FROM PUBLIC;

DROP FUNCTION IF EXISTS gongmcp_profile_call_fact_summary(bigint, text, text, text, text, text, text, text, integer);
CREATE OR REPLACE FUNCTION gongmcp_profile_call_fact_summary(profile_id_arg bigint, canonical_sha_arg text, group_by_arg text, lifecycle_bucket_arg text, scope_arg text, system_arg text, direction_arg text, transcript_status_arg text, row_limit integer)
RETURNS TABLE(
	group_by text,
	group_value text,
	call_count bigint,
	transcript_count bigint,
	missing_transcript_count bigint,
	opportunity_call_count bigint,
	account_call_count bigint,
	external_call_count bigint,
	internal_call_count bigint,
	unknown_scope_call_count bigint,
	total_duration_seconds bigint,
	avg_duration_seconds double precision,
	latest_call_at text
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $function$
WITH args AS (
	SELECT CASE lower(trim(COALESCE(group_by_arg, '')))
		WHEN '' THEN 'lifecycle'
		WHEN 'lifecycle_bucket' THEN 'lifecycle'
		WHEN 'lifecycle' THEN 'lifecycle'
		WHEN 'stage' THEN 'deal_stage'
		WHEN 'opportunity_stage' THEN 'deal_stage'
		WHEN 'deal_stage' THEN 'deal_stage'
		WHEN 'opportunity_type' THEN 'deal_type'
		WHEN 'deal_type' THEN 'deal_type'
		WHEN 'account_type' THEN 'account_type'
		WHEN 'industry' THEN 'account_industry'
		WHEN 'account_industry' THEN 'account_industry'
		WHEN 'revenue_range' THEN 'account_revenue_range'
		WHEN 'account_revenue_range' THEN 'account_revenue_range'
		WHEN 'scope' THEN 'scope'
		WHEN 'system' THEN 'system'
		WHEN 'direction' THEN 'direction'
		WHEN 'transcript_status' THEN 'transcript_status'
		WHEN 'calendar' THEN 'calendar'
		WHEN 'calendar_event_status' THEN 'calendar'
		WHEN 'duration_bucket' THEN 'duration_bucket'
		WHEN 'month' THEN 'month'
		WHEN 'call_month' THEN 'month'
		WHEN 'lead_source' THEN 'lead_source'
		WHEN 'primary_lead_source' THEN 'lead_source'
		WHEN 'forecast_category' THEN 'forecast_category'
		ELSE ''
	END AS group_by
),
filtered AS (
	SELECT c.*,
	       a.group_by,
	       CASE a.group_by
		       WHEN 'lifecycle' THEN COALESCE(NULLIF(c.lifecycle_bucket, ''), '<blank>')
		       WHEN 'scope' THEN COALESCE(NULLIF(c.scope, ''), '<blank>')
		       WHEN 'system' THEN COALESCE(NULLIF(c.system, ''), '<blank>')
		       WHEN 'direction' THEN COALESCE(NULLIF(c.direction, ''), '<blank>')
		       WHEN 'transcript_status' THEN CASE WHEN c.transcript_present THEN 'present' ELSE 'missing' END
		       WHEN 'duration_bucket' THEN CASE WHEN c.duration_seconds < 60 THEN 'under_1m' WHEN c.duration_seconds < 300 THEN '1_5m' WHEN c.duration_seconds < 900 THEN '5_15m' WHEN c.duration_seconds < 1800 THEN '15_30m' WHEN c.duration_seconds < 2700 THEN '30_45m' ELSE '45m_plus' END
		       WHEN 'month' THEN COALESCE(NULLIF(left(c.started_at, 7), ''), '<blank>')
		       WHEN 'calendar' THEN CASE WHEN c.calendar_event_present THEN 'calendar' ELSE 'no_calendar' END
		       WHEN 'deal_stage' THEN COALESCE(NULLIF(jsonb_extract_path_text(c.field_values_json, 'deal_stage', '0'), ''), '<blank>')
		       WHEN 'deal_type' THEN COALESCE(NULLIF(jsonb_extract_path_text(c.field_values_json, 'deal_type', '0'), ''), '<blank>')
		       WHEN 'account_type' THEN COALESCE(NULLIF(jsonb_extract_path_text(c.field_values_json, 'account_type', '0'), ''), '<blank>')
		       WHEN 'account_industry' THEN COALESCE(NULLIF(jsonb_extract_path_text(c.field_values_json, 'account_industry', '0'), ''), '<blank>')
		       WHEN 'account_revenue_range' THEN COALESCE(NULLIF(jsonb_extract_path_text(c.field_values_json, 'account_revenue_range', '0'), ''), '<blank>')
		       WHEN 'lead_source' THEN COALESCE(NULLIF(jsonb_extract_path_text(c.field_values_json, 'lead_source', '0'), ''), '<blank>')
		       WHEN 'forecast_category' THEN COALESCE(NULLIF(jsonb_extract_path_text(c.field_values_json, 'forecast_category', '0'), ''), '<blank>')
		       ELSE '<blank>'
	       END AS group_value
		  FROM profile_call_fact_cache c
		  JOIN profile_meta p
		    ON p.id = c.profile_id
		  CROSS JOIN args a
		 WHERE p.is_active = true
		   AND a.group_by <> ''
		   AND c.profile_id = profile_id_arg
		   AND (canonical_sha_arg = '' OR c.canonical_sha256 = canonical_sha_arg)
	   AND (lifecycle_bucket_arg = '' OR c.lifecycle_bucket = lifecycle_bucket_arg)
	   AND (scope_arg = '' OR c.scope = scope_arg)
	   AND (system_arg = '' OR c.system = system_arg)
	   AND (direction_arg = '' OR c.direction = direction_arg)
	   AND (transcript_status_arg = '' OR (transcript_status_arg = 'present' AND c.transcript_present) OR (transcript_status_arg = 'missing' AND NOT c.transcript_present))
)
SELECT filtered.group_by AS group_by,
	       filtered.group_value AS group_value,
       COUNT(*) AS call_count,
       COALESCE(SUM(CASE WHEN transcript_present THEN 1 ELSE 0 END), 0) AS transcript_count,
       COALESCE(SUM(CASE WHEN NOT transcript_present THEN 1 ELSE 0 END), 0) AS missing_transcript_count,
       COALESCE(SUM(CASE WHEN deal_count > 0 THEN 1 ELSE 0 END), 0) AS opportunity_call_count,
       COALESCE(SUM(CASE WHEN account_count > 0 THEN 1 ELSE 0 END), 0) AS account_call_count,
       COALESCE(SUM(CASE WHEN scope = 'External' THEN 1 ELSE 0 END), 0) AS external_call_count,
       COALESCE(SUM(CASE WHEN scope = 'Internal' THEN 1 ELSE 0 END), 0) AS internal_call_count,
       COALESCE(SUM(CASE WHEN scope NOT IN ('External', 'Internal') THEN 1 ELSE 0 END), 0) AS unknown_scope_call_count,
       COALESCE(SUM(duration_seconds), 0) AS total_duration_seconds,
       COALESCE(AVG(duration_seconds), 0) AS avg_duration_seconds,
       COALESCE(MAX(started_at), '') AS latest_call_at
  FROM filtered
 GROUP BY filtered.group_by, filtered.group_value
 ORDER BY call_count DESC, filtered.group_value
 LIMIT LEAST(GREATEST(COALESCE(row_limit, 25), 1), 1000)
$function$;

REVOKE ALL ON FUNCTION gongmcp_profile_call_fact_summary(bigint, text, text, text, text, text, text, text, integer) FROM PUBLIC;

CREATE OR REPLACE FUNCTION gongmcp_profile_call_fact_summary_sanitized(profile_id_arg bigint, canonical_sha_arg text, group_by_arg text, lifecycle_bucket_arg text, scope_arg text, system_arg text, direction_arg text, transcript_status_arg text, row_limit integer)
RETURNS TABLE(
	group_by text,
	group_value text,
	call_count bigint,
	transcript_count bigint,
	missing_transcript_count bigint,
	opportunity_call_count bigint,
	account_call_count bigint,
	external_call_count bigint,
	internal_call_count bigint,
	unknown_scope_call_count bigint,
	total_duration_seconds bigint,
	avg_duration_seconds double precision,
	latest_call_at text
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $function$
DECLARE
	safe_group_by text;
BEGIN
safe_group_by := CASE lower(trim(COALESCE(group_by_arg, '')))
	WHEN '' THEN 'lifecycle'
	WHEN 'lifecycle_bucket' THEN 'lifecycle'
	WHEN 'lifecycle' THEN 'lifecycle'
	WHEN 'scope' THEN 'scope'
	WHEN 'system' THEN 'system'
	WHEN 'direction' THEN 'direction'
	WHEN 'transcript_status' THEN 'transcript_status'
	WHEN 'calendar' THEN 'calendar'
	WHEN 'calendar_event_status' THEN 'calendar'
	WHEN 'duration_bucket' THEN 'duration_bucket'
	WHEN 'month' THEN 'month'
	WHEN 'call_month' THEN 'month'
	ELSE ''
END;
IF safe_group_by = '' THEN
	RAISE EXCEPTION 'group_by % is not supported by the business-pilot scoped Postgres reader', group_by_arg;
END IF;
RETURN QUERY
SELECT s.group_by,
       s.group_value,
       s.call_count,
       s.transcript_count,
       s.missing_transcript_count,
       s.opportunity_call_count,
       s.account_call_count,
       s.external_call_count,
       s.internal_call_count,
       s.unknown_scope_call_count,
       s.total_duration_seconds,
       s.avg_duration_seconds,
       s.latest_call_at
  FROM gongmcp_profile_call_fact_summary(
	profile_id_arg,
	canonical_sha_arg,
	safe_group_by,
	lifecycle_bucket_arg,
	scope_arg,
	system_arg,
	direction_arg,
	transcript_status_arg,
	row_limit
  ) AS s;
END
$function$;
REVOKE ALL ON FUNCTION gongmcp_profile_call_fact_summary_sanitized(bigint, text, text, text, text, text, text, text, integer) FROM PUBLIC;

CREATE OR REPLACE FUNCTION gongmcp_profile_lifecycle_summary_sanitized(profile_id_arg bigint, canonical_sha_arg text, bucket_arg text)
RETURNS TABLE(
	bucket text,
	call_count bigint,
	transcript_count bigint,
	missing_transcript_count bigint,
	opportunity_call_count bigint,
	account_call_count bigint,
	total_duration_seconds bigint,
	latest_call_id text,
	latest_call_at text,
	high_confidence_calls bigint,
	medium_confidence_calls bigint,
	low_confidence_calls bigint
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $function$
SELECT c.lifecycle_bucket AS bucket,
       COUNT(*) AS call_count,
       COALESCE(SUM(CASE WHEN c.transcript_present THEN 1 ELSE 0 END), 0) AS transcript_count,
       COALESCE(SUM(CASE WHEN NOT c.transcript_present THEN 1 ELSE 0 END), 0) AS missing_transcript_count,
       COALESCE(SUM(CASE WHEN c.deal_count > 0 THEN 1 ELSE 0 END), 0) AS opportunity_call_count,
       COALESCE(SUM(CASE WHEN c.account_count > 0 THEN 1 ELSE 0 END), 0) AS account_call_count,
       COALESCE(SUM(c.duration_seconds), 0) AS total_duration_seconds,
       ''::text AS latest_call_id,
       COALESCE(MAX(c.started_at), '') AS latest_call_at,
       COALESCE(SUM(CASE WHEN c.lifecycle_confidence = 'high' THEN 1 ELSE 0 END), 0) AS high_confidence_calls,
       COALESCE(SUM(CASE WHEN c.lifecycle_confidence = 'medium' THEN 1 ELSE 0 END), 0) AS medium_confidence_calls,
       COALESCE(SUM(CASE WHEN c.lifecycle_confidence NOT IN ('high', 'medium') THEN 1 ELSE 0 END), 0) AS low_confidence_calls
  FROM profile_call_fact_cache c
  JOIN profile_meta p
    ON p.id = c.profile_id
 WHERE p.is_active = true
   AND c.profile_id = profile_id_arg
   AND (canonical_sha_arg = '' OR c.canonical_sha256 = canonical_sha_arg)
   AND (bucket_arg = '' OR c.lifecycle_bucket = bucket_arg)
 GROUP BY c.lifecycle_bucket
$function$;
REVOKE ALL ON FUNCTION gongmcp_profile_lifecycle_summary_sanitized(bigint, text, text) FROM PUBLIC;

CREATE OR REPLACE FUNCTION gongmcp_profile_transcript_backlog_sanitized(profile_id_arg bigint, canonical_sha_arg text, bucket_arg text, from_date_arg text, to_date_arg text, scope_arg text, system_arg text, direction_arg text, row_limit integer)
RETURNS TABLE(
	call_id text,
	title text,
	started_at text,
	duration_seconds bigint,
	system text,
	direction text,
	scope text,
	bucket text,
	confidence text,
	reason text,
	evidence_fields_json jsonb,
	priority_score bigint
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $function$
WITH lifecycle_order AS (
	SELECT bucket, COALESCE(MAX(ordinal), 500) AS ordinal
	  FROM profile_lifecycle_rule
	 WHERE profile_id = profile_id_arg
	 GROUP BY bucket
),
ranked AS (
	SELECT ''::text AS call_id,
	       ''::text AS title,
	       c.started_at,
	       c.duration_seconds,
	       c.system,
	       c.direction,
	       c.scope,
	       c.lifecycle_bucket AS bucket,
	       c.lifecycle_confidence AS confidence,
	       c.lifecycle_reason AS reason,
	       c.evidence_fields_json,
	       (
	         (100 - COALESCE(lo.ordinal, 500))
	         + CASE WHEN c.lifecycle_bucket IN ('closed_won', 'closed_lost', 'post_sales') THEN 50 ELSE 0 END
	         + CASE WHEN c.lifecycle_confidence = 'high' THEN 20 ELSE 0 END
	         + CASE WHEN c.scope = 'External' THEN 25 ELSE 0 END
	         + CASE WHEN c.direction = 'Conference' THEN 20 ELSE 0 END
	         + CASE WHEN c.duration_seconds >= 1800 THEN 20 WHEN c.duration_seconds >= 600 THEN 10 ELSE 0 END
	         + CASE WHEN c.deal_count > 0 THEN 10 ELSE 0 END
	         - CASE WHEN c.duration_seconds > 0 AND c.duration_seconds < 300 AND c.direction <> 'Conference' THEN 20 ELSE 0 END
	       )::bigint AS priority_score
	  FROM profile_call_fact_cache c
	  JOIN profile_meta p
	    ON p.id = c.profile_id
	  LEFT JOIN lifecycle_order lo
	    ON lo.bucket = c.lifecycle_bucket
	 WHERE p.is_active = true
	   AND c.profile_id = profile_id_arg
	   AND (canonical_sha_arg = '' OR c.canonical_sha256 = canonical_sha_arg)
	   AND NOT c.transcript_present
	   AND (bucket_arg = '' OR c.lifecycle_bucket = bucket_arg)
	   AND (from_date_arg = '' OR c.started_at >= from_date_arg)
	   AND (to_date_arg = '' OR c.started_at < ((NULLIF(to_date_arg, '')::date + INTERVAL '1 day')::date::text))
	   AND (scope_arg = '' OR c.scope = scope_arg)
	   AND (system_arg = '' OR c.system = system_arg)
	   AND (direction_arg = '' OR c.direction = direction_arg)
)
SELECT call_id, title, started_at, duration_seconds, system, direction, scope,
       bucket, confidence, reason, evidence_fields_json, priority_score
  FROM ranked
 ORDER BY priority_score DESC, started_at DESC, call_id
 LIMIT LEAST(GREATEST(COALESCE(row_limit, 25), 1), 1000)
$function$;
REVOKE ALL ON FUNCTION gongmcp_profile_transcript_backlog_sanitized(bigint, text, text, text, text, text, text, text, integer) FROM PUBLIC;

`,
	`
CREATE TABLE IF NOT EXISTS governance_policy_state (
	config_sha256 TEXT PRIMARY KEY,
	data_fingerprint TEXT NOT NULL,
	config_entries INTEGER NOT NULL DEFAULT 0,
	config_aliases INTEGER NOT NULL DEFAULT 0,
	matched_entries INTEGER NOT NULL DEFAULT 0,
	unmatched_entries INTEGER NOT NULL DEFAULT 0,
	suppressed_call_count INTEGER NOT NULL DEFAULT 0,
	updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS governance_suppressed_calls (
	config_sha256 TEXT NOT NULL REFERENCES governance_policy_state(config_sha256) ON DELETE CASCADE,
	call_id TEXT NOT NULL,
	PRIMARY KEY(config_sha256, call_id)
);

CREATE INDEX IF NOT EXISTS idx_pg_governance_suppressed_calls_call_id
	ON governance_suppressed_calls(call_id);

CREATE OR REPLACE FUNCTION gongmcp_governance_data_fingerprint()
RETURNS text
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $function$
WITH candidates AS (
	SELECT call_id, 'call_title' AS source, title AS value
	  FROM calls
	 WHERE TRIM(title) <> ''
	UNION ALL
	SELECT call_id, 'call_raw_json' AS source, raw_json::text AS value
	  FROM calls
	 WHERE TRIM(raw_json::text) <> ''
	UNION ALL
	SELECT call_id, 'crm_object_name' AS source, object_name AS value
	  FROM call_context_objects
	 WHERE TRIM(object_name) <> ''
	UNION ALL
	SELECT call_id, 'crm_field:' || field_name AS source, field_value_text AS value
	  FROM call_context_fields
	 WHERE TRIM(field_value_text) <> ''
	UNION ALL
	SELECT call_id, 'transcript_segment' AS source, text AS value
	  FROM transcript_segments
	 WHERE TRIM(text) <> ''
)
SELECT 'candidates:' || COUNT(*)::text || ':' ||
       COALESCE(md5(string_agg(call_id || chr(31) || source || chr(31) || TRIM(value), chr(30) ORDER BY call_id, source, value)), md5(''))
  FROM candidates
$function$;

CREATE OR REPLACE FUNCTION gongmcp_governance_policy_state(config_sha_arg text)
RETURNS TABLE(
	config_sha256 text,
	data_fingerprint text,
	config_entries integer,
	config_aliases integer,
	matched_entries integer,
	unmatched_entries integer,
	suppressed_call_count integer,
	updated_at text
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $function$
SELECT p.config_sha256,
       p.data_fingerprint,
       p.config_entries,
       p.config_aliases,
       p.matched_entries,
       p.unmatched_entries,
       p.suppressed_call_count,
       p.updated_at
  FROM governance_policy_state p
 WHERE p.config_sha256 = config_sha_arg
$function$;

CREATE OR REPLACE FUNCTION gongmcp_governance_suppressed_call_ids(config_sha_arg text)
RETURNS TABLE(call_id text)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $function$
SELECT s.call_id
  FROM governance_suppressed_calls s
 WHERE s.config_sha256 = config_sha_arg
$function$;

REVOKE ALL ON FUNCTION gongmcp_governance_data_fingerprint() FROM PUBLIC;
REVOKE ALL ON FUNCTION gongmcp_governance_policy_state(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION gongmcp_governance_suppressed_call_ids(text) FROM PUBLIC;

DO $$
BEGIN
	IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'gongmcp_reader') THEN
		EXECUTE 'REVOKE ALL PRIVILEGES ON TABLE governance_policy_state FROM gongmcp_reader';
		EXECUTE 'REVOKE ALL PRIVILEGES ON TABLE governance_suppressed_calls FROM gongmcp_reader';
		EXECUTE 'GRANT EXECUTE ON FUNCTION gongmcp_governance_data_fingerprint() TO gongmcp_reader';
		EXECUTE 'GRANT EXECUTE ON FUNCTION gongmcp_governance_policy_state(text) TO gongmcp_reader';
		EXECUTE 'GRANT EXECUTE ON FUNCTION gongmcp_governance_suppressed_call_ids(text) TO gongmcp_reader';
	END IF;
END;
$$;

`,
	`
CREATE OR REPLACE FUNCTION gongmcp_crm_field_summary(object_type_arg text, row_limit integer)
RETURNS TABLE(
	object_type text,
	field_name text,
	field_label text,
	row_count bigint,
	call_count bigint,
	populated_count bigint,
	distinct_value_count bigint
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $function$
SELECT o.object_type,
       f.field_name,
       MAX(f.field_label) AS field_label,
       COUNT(*) AS row_count,
       COUNT(DISTINCT f.call_id) AS call_count,
       COUNT(NULLIF(TRIM(f.field_value_text), '')) AS populated_count,
       COUNT(DISTINCT NULLIF(TRIM(f.field_value_text), '')) AS distinct_value_count
  FROM call_context_fields f
  JOIN call_context_objects o
    ON o.call_id = f.call_id
   AND o.object_key = f.object_key
 WHERE o.object_type = object_type_arg
 GROUP BY o.object_type, f.field_name
 ORDER BY row_count DESC, f.field_name
 LIMIT LEAST(GREATEST(COALESCE(row_limit, 50), 1), 1000)
$function$;

REVOKE ALL ON FUNCTION gongmcp_crm_field_summary(text, integer) FROM PUBLIC;

DO $$
BEGIN
	IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'gongmcp_reader') THEN
		EXECUTE 'GRANT EXECUTE ON FUNCTION gongmcp_crm_field_summary(text, integer) TO gongmcp_reader';
	END IF;
END;
$$;

`,
	`
DROP FUNCTION IF EXISTS gongmcp_crm_field_summary(text, integer);

	`,
	postgresBusinessAnalysisFunctionsSQL + postgresBusinessAnalysisReaderGrantsSQL + `
`,
	postgresSettingsMigrationSQL + postgresSettingsFunctionsSQL + postgresSettingsReaderGrantsSQL + `
`,
	postgresScorecardActivityMigrationSQL + postgresScorecardActivityFunctionsSQL + postgresScorecardActivityReaderGrantsSQL + `
`,
	postgresCRMInventoryMigrationSQL + postgresCRMInventoryReaderGrantsSQL + `
`,
	`
CREATE TABLE IF NOT EXISTS purged_call_ids (
	call_id TEXT PRIMARY KEY,
	started_at TEXT NOT NULL DEFAULT '',
	purge_started_before TEXT NOT NULL DEFAULT '',
	purged_at TEXT NOT NULL
);

CREATE OR REPLACE FUNCTION gongmcp_cache_purge_plan(started_before_arg text)
RETURNS TABLE(
	call_count bigint,
	transcript_count bigint,
	transcript_segment_count bigint,
	context_object_count bigint,
	context_field_count bigint,
	call_fact_count bigint,
	read_model_diagnostic_count bigint,
	profile_call_fact_count bigint,
	scorecard_activity_count bigint,
	governance_suppressed_call_count bigint
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $function$
WITH purge_calls AS (
	SELECT call_id
	  FROM calls
	 WHERE TRIM(started_at) <> ''
	   AND started_at < started_before_arg
)
SELECT
	(SELECT COUNT(*) FROM purge_calls),
	(SELECT COUNT(*) FROM transcripts WHERE call_id IN (SELECT call_id FROM purge_calls)),
	(SELECT COUNT(*) FROM transcript_segments WHERE call_id IN (SELECT call_id FROM purge_calls)),
	(SELECT COUNT(*) FROM call_context_objects WHERE call_id IN (SELECT call_id FROM purge_calls)),
	(SELECT COUNT(*) FROM call_context_fields WHERE call_id IN (SELECT call_id FROM purge_calls)),
	(SELECT COUNT(*) FROM call_facts WHERE call_id IN (SELECT call_id FROM purge_calls)),
	(SELECT COUNT(*) FROM call_read_model_diagnostics WHERE call_id IN (SELECT call_id FROM purge_calls)),
	(SELECT COUNT(*) FROM profile_call_fact_cache WHERE call_id IN (SELECT call_id FROM purge_calls)),
	(SELECT COUNT(*) FROM scorecard_activity WHERE call_id IN (SELECT call_id FROM purge_calls)),
	(SELECT COUNT(*) FROM governance_suppressed_calls WHERE call_id IN (SELECT call_id FROM purge_calls))
$function$;

REVOKE ALL ON FUNCTION gongmcp_cache_purge_plan(text) FROM PUBLIC;

DO $$
BEGIN
	IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'gongmcp_reader') THEN
		EXECUTE 'GRANT EXECUTE ON FUNCTION gongmcp_cache_purge_plan(text) TO gongmcp_reader';
	END IF;
END;
$$;
`,
	`
	CREATE INDEX IF NOT EXISTS idx_pg_profile_call_fact_cache_call
		ON profile_call_fact_cache(call_id);
	`,
	`
DROP FUNCTION IF EXISTS gongmcp_crm_field_value_search(text, text, text, integer);
DROP FUNCTION IF EXISTS gongmcp_crm_field_value_search(text, text, text, integer, boolean, boolean);
DROP FUNCTION IF EXISTS gongmcp_crm_object_type_summary();
DROP FUNCTION IF EXISTS gongmcp_crm_field_summary_sanitized(text, integer);
` + postgresCRMObjectTypeSummaryFunctionSQL + `
` + postgresCRMFieldSummaryFunctionSQL + `
` + postgresCRMFieldValueSearchFunctionSQL + `
DO $$
BEGIN
	IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'gongmcp_reader') THEN
		EXECUTE 'GRANT EXECUTE ON FUNCTION gongmcp_crm_object_type_summary() TO gongmcp_reader';
		EXECUTE 'GRANT EXECUTE ON FUNCTION gongmcp_crm_field_summary_sanitized(text, integer) TO gongmcp_reader';
		EXECUTE 'GRANT EXECUTE ON FUNCTION gongmcp_crm_field_value_search(text, text, text, integer, boolean, boolean) TO gongmcp_reader';
	END IF;
END;
$$;
`,
	`
DROP FUNCTION IF EXISTS gongmcp_unmapped_crm_field_inventory(integer);
` + postgresUnmappedCRMFieldInventoryFunctionSQL + `
DO $$
BEGIN
	IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'gongmcp_reader') THEN
		EXECUTE 'GRANT EXECUTE ON FUNCTION gongmcp_unmapped_crm_field_inventory(integer) TO gongmcp_reader';
	END IF;
END;
$$;
`,
	`
DROP FUNCTION IF EXISTS gongmcp_late_stage_call_counts(text, text, text);
DROP FUNCTION IF EXISTS gongmcp_late_stage_stage_counts(text, text, text);
DROP FUNCTION IF EXISTS gongmcp_late_stage_signal_inventory(text, text, text, integer, boolean);
` + postgresLateStageSignalFunctionsSQL + `
DO $$
BEGIN
	IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'gongmcp_reader') THEN
		EXECUTE 'GRANT EXECUTE ON FUNCTION gongmcp_late_stage_call_counts(text, text, text) TO gongmcp_reader';
		EXECUTE 'GRANT EXECUTE ON FUNCTION gongmcp_late_stage_stage_counts(text, text, text) TO gongmcp_reader';
		EXECUTE 'GRANT EXECUTE ON FUNCTION gongmcp_late_stage_signal_inventory(text, text, text, integer, boolean) TO gongmcp_reader';
	END IF;
END;
$$;
`,
	`
DROP FUNCTION IF EXISTS gongmcp_opportunities_missing_transcripts(text, integer);
` + postgresOpportunitiesMissingTranscriptsFunctionSQL + `
DO $$
BEGIN
	IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'gongmcp_reader') THEN
		EXECUTE 'GRANT EXECUTE ON FUNCTION gongmcp_opportunities_missing_transcripts(text, integer) TO gongmcp_reader';
	END IF;
END;
$$;
`,
	`
DROP FUNCTION IF EXISTS gongmcp_opportunity_call_summary(text, integer);
` + postgresOpportunityCallSummaryFunctionSQL + `
DO $$
BEGIN
	IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'gongmcp_reader') THEN
		EXECUTE 'GRANT EXECUTE ON FUNCTION gongmcp_opportunity_call_summary(text, integer) TO gongmcp_reader';
	END IF;
END;
$$;
`,
	`
DROP FUNCTION IF EXISTS gongmcp_crm_field_population_matrix(text, text, integer);
` + postgresCRMFieldPopulationMatrixFunctionSQL + `
DO $$
BEGIN
	IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'gongmcp_reader') THEN
		EXECUTE 'GRANT EXECUTE ON FUNCTION gongmcp_crm_field_population_matrix(text, text, integer) TO gongmcp_reader';
	END IF;
END;
$$;
`,
	`
DROP FUNCTION IF EXISTS gongmcp_search_transcript_segments_by_crm_context(text, text, text, integer);
` + postgresTranscriptCRMContextSearchFunctionSQL + `
DO $$
BEGIN
	IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'gongmcp_reader') THEN
		EXECUTE 'GRANT EXECUTE ON FUNCTION gongmcp_search_transcript_segments_by_crm_context(text, text, text, integer) TO gongmcp_reader';
	END IF;
END;
$$;
	`,
	`
DROP FUNCTION IF EXISTS gongmcp_missing_transcripts(text, text, text, text, text, text, text, text, integer);
CREATE TABLE IF NOT EXISTS governance_ingest_skipped_calls (
	call_id TEXT PRIMARY KEY,
	config_sha256 TEXT NOT NULL,
	matched_list TEXT NOT NULL,
	source_category TEXT NOT NULL,
	run_id BIGINT,
	skipped_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_pg_governance_ingest_skipped_calls_config
	ON governance_ingest_skipped_calls(config_sha256);
` + postgresMissingTranscriptsFunctionSQL + postgresMissingTranscriptCountFunctionSQL + `
DO $$
BEGIN
	IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'gongmcp_reader') THEN
		EXECUTE 'GRANT EXECUTE ON FUNCTION gongmcp_missing_transcripts(text, text, text, text, text, text, text, text, integer) TO gongmcp_reader';
		EXECUTE 'GRANT EXECUTE ON FUNCTION gongmcp_missing_transcript_count() TO gongmcp_reader';
	END IF;
END;
$$;
`,
	`
DROP FUNCTION IF EXISTS gongmcp_compare_lifecycle_crm_fields(text, text, text, integer);
` + postgresLifecycleCRMFieldComparisonFunctionSQL + `
DO $$
BEGIN
	IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'gongmcp_reader') THEN
		EXECUTE 'GRANT EXECUTE ON FUNCTION gongmcp_compare_lifecycle_crm_fields(text, text, text, integer) TO gongmcp_reader';
	END IF;
END;
$$;
`,
	`
DROP FUNCTION IF EXISTS gongmcp_profile_call_fact_cache_meta_sanitized(bigint);
CREATE OR REPLACE FUNCTION gongmcp_profile_call_fact_cache_meta_sanitized(profile_id_arg bigint)
RETURNS TABLE(data_fingerprint text, built_at text, call_count bigint)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $function$
SELECT m.data_fingerprint, m.built_at, m.call_count
  FROM profile_call_fact_cache_meta m
  JOIN profile_meta p
    ON p.id = m.profile_id
 WHERE p.is_active = true
   AND m.profile_id = profile_id_arg
 ORDER BY m.built_at DESC, m.canonical_sha256 DESC
 LIMIT 1
$function$;
REVOKE ALL ON FUNCTION gongmcp_profile_call_fact_cache_meta_sanitized(bigint) FROM PUBLIC;

DROP FUNCTION IF EXISTS gongmcp_profile_call_fact_cache_sanitized(bigint, text);
CREATE OR REPLACE FUNCTION gongmcp_profile_call_fact_cache_sanitized(profile_id_arg bigint, canonical_sha_arg text)
RETURNS TABLE(
	call_id text,
	title text,
	started_at text,
	duration_seconds bigint,
	system text,
	direction text,
	scope text,
	purpose text,
	calendar_event_present boolean,
	transcript_present boolean,
	lifecycle_bucket text,
	lifecycle_confidence text,
	lifecycle_reason text,
	evidence_fields_json jsonb,
	deal_count bigint,
	account_count bigint
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $function$
SELECT ''::text AS call_id,
       ''::text AS title,
       c.started_at,
       c.duration_seconds,
       c.system,
       c.direction,
       c.scope,
       c.purpose,
       c.calendar_event_present,
       c.transcript_present,
       c.lifecycle_bucket,
       c.lifecycle_confidence,
       c.lifecycle_reason,
       c.evidence_fields_json,
       c.deal_count,
       c.account_count
  FROM profile_call_fact_cache c
  JOIN profile_meta p
    ON p.id = c.profile_id
 WHERE p.is_active = true
   AND c.profile_id = profile_id_arg
   AND (canonical_sha_arg = '' OR c.canonical_sha256 = canonical_sha_arg)
$function$;
REVOKE ALL ON FUNCTION gongmcp_profile_call_fact_cache_sanitized(bigint, text) FROM PUBLIC;
DROP FUNCTION IF EXISTS gongmcp_profile_call_fact_cache_sanitized_limited(bigint, text, integer);
CREATE OR REPLACE FUNCTION gongmcp_profile_call_fact_cache_sanitized_limited(profile_id_arg bigint, canonical_sha_arg text, row_limit integer)
RETURNS TABLE(
	call_id text,
	title text,
	started_at text,
	duration_seconds bigint,
	system text,
	direction text,
	scope text,
	purpose text,
	calendar_event_present boolean,
	transcript_present boolean,
	lifecycle_bucket text,
	lifecycle_confidence text,
	lifecycle_reason text,
	evidence_fields_json jsonb,
	deal_count bigint,
	account_count bigint
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $function$
SELECT ''::text AS call_id,
       ''::text AS title,
       c.started_at,
       c.duration_seconds,
       c.system,
       c.direction,
       c.scope,
       c.purpose,
       c.calendar_event_present,
       c.transcript_present,
       c.lifecycle_bucket,
       c.lifecycle_confidence,
       c.lifecycle_reason,
       c.evidence_fields_json,
       c.deal_count,
       c.account_count
  FROM profile_call_fact_cache c
  JOIN profile_meta p
    ON p.id = c.profile_id
 WHERE p.is_active = true
   AND c.profile_id = profile_id_arg
   AND (canonical_sha_arg = '' OR c.canonical_sha256 = canonical_sha_arg)
 ORDER BY c.started_at DESC, c.call_id
 LIMIT LEAST(GREATEST(COALESCE(row_limit, 1000), 1), 1000)
$function$;
REVOKE ALL ON FUNCTION gongmcp_profile_call_fact_cache_sanitized_limited(bigint, text, integer) FROM PUBLIC;

CREATE OR REPLACE FUNCTION gongmcp_profile_call_fact_summary_sanitized(profile_id_arg bigint, canonical_sha_arg text, group_by_arg text, lifecycle_bucket_arg text, scope_arg text, system_arg text, direction_arg text, transcript_status_arg text, row_limit integer)
RETURNS TABLE(
	group_by text,
	group_value text,
	call_count bigint,
	transcript_count bigint,
	missing_transcript_count bigint,
	opportunity_call_count bigint,
	account_call_count bigint,
	external_call_count bigint,
	internal_call_count bigint,
	unknown_scope_call_count bigint,
	total_duration_seconds bigint,
	avg_duration_seconds double precision,
	latest_call_at text
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $function$
DECLARE
	safe_group_by text;
BEGIN
safe_group_by := CASE lower(trim(COALESCE(group_by_arg, '')))
	WHEN '' THEN 'lifecycle'
	WHEN 'lifecycle_bucket' THEN 'lifecycle'
	WHEN 'lifecycle' THEN 'lifecycle'
	WHEN 'scope' THEN 'scope'
	WHEN 'system' THEN 'system'
	WHEN 'direction' THEN 'direction'
	WHEN 'transcript_status' THEN 'transcript_status'
	WHEN 'calendar' THEN 'calendar'
	WHEN 'calendar_event_status' THEN 'calendar'
	WHEN 'duration_bucket' THEN 'duration_bucket'
	WHEN 'month' THEN 'month'
	WHEN 'call_month' THEN 'month'
	ELSE ''
END;
IF safe_group_by = '' THEN
	RAISE EXCEPTION 'group_by % is not supported by the business-pilot scoped Postgres reader', group_by_arg;
END IF;
RETURN QUERY
SELECT s.group_by,
       s.group_value,
       s.call_count,
       s.transcript_count,
       s.missing_transcript_count,
       s.opportunity_call_count,
       s.account_call_count,
       s.external_call_count,
       s.internal_call_count,
       s.unknown_scope_call_count,
       s.total_duration_seconds,
       s.avg_duration_seconds,
       s.latest_call_at
  FROM gongmcp_profile_call_fact_summary(
	profile_id_arg,
	canonical_sha_arg,
	safe_group_by,
	lifecycle_bucket_arg,
	scope_arg,
	system_arg,
	direction_arg,
	transcript_status_arg,
	row_limit
  ) AS s;
END
$function$;
REVOKE ALL ON FUNCTION gongmcp_profile_call_fact_summary_sanitized(bigint, text, text, text, text, text, text, text, integer) FROM PUBLIC;

CREATE OR REPLACE FUNCTION gongmcp_profile_lifecycle_summary_sanitized(profile_id_arg bigint, canonical_sha_arg text, bucket_arg text)
RETURNS TABLE(
	bucket text,
	call_count bigint,
	transcript_count bigint,
	missing_transcript_count bigint,
	opportunity_call_count bigint,
	account_call_count bigint,
	total_duration_seconds bigint,
	latest_call_id text,
	latest_call_at text,
	high_confidence_calls bigint,
	medium_confidence_calls bigint,
	low_confidence_calls bigint
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $function$
SELECT c.lifecycle_bucket AS bucket,
       COUNT(*) AS call_count,
       COALESCE(SUM(CASE WHEN c.transcript_present THEN 1 ELSE 0 END), 0) AS transcript_count,
       COALESCE(SUM(CASE WHEN NOT c.transcript_present THEN 1 ELSE 0 END), 0) AS missing_transcript_count,
       COALESCE(SUM(CASE WHEN c.deal_count > 0 THEN 1 ELSE 0 END), 0) AS opportunity_call_count,
       COALESCE(SUM(CASE WHEN c.account_count > 0 THEN 1 ELSE 0 END), 0) AS account_call_count,
       COALESCE(SUM(c.duration_seconds), 0) AS total_duration_seconds,
       ''::text AS latest_call_id,
       COALESCE(MAX(c.started_at), '') AS latest_call_at,
       COALESCE(SUM(CASE WHEN c.lifecycle_confidence = 'high' THEN 1 ELSE 0 END), 0) AS high_confidence_calls,
       COALESCE(SUM(CASE WHEN c.lifecycle_confidence = 'medium' THEN 1 ELSE 0 END), 0) AS medium_confidence_calls,
       COALESCE(SUM(CASE WHEN c.lifecycle_confidence NOT IN ('high', 'medium') THEN 1 ELSE 0 END), 0) AS low_confidence_calls
  FROM profile_call_fact_cache c
  JOIN profile_meta p
    ON p.id = c.profile_id
 WHERE p.is_active = true
   AND c.profile_id = profile_id_arg
   AND (canonical_sha_arg = '' OR c.canonical_sha256 = canonical_sha_arg)
   AND (bucket_arg = '' OR c.lifecycle_bucket = bucket_arg)
 GROUP BY c.lifecycle_bucket
$function$;
REVOKE ALL ON FUNCTION gongmcp_profile_lifecycle_summary_sanitized(bigint, text, text) FROM PUBLIC;

CREATE OR REPLACE FUNCTION gongmcp_profile_transcript_backlog_sanitized(profile_id_arg bigint, canonical_sha_arg text, bucket_arg text, from_date_arg text, to_date_arg text, scope_arg text, system_arg text, direction_arg text, row_limit integer)
RETURNS TABLE(
	call_id text,
	title text,
	started_at text,
	duration_seconds bigint,
	system text,
	direction text,
	scope text,
	bucket text,
	confidence text,
	reason text,
	evidence_fields_json jsonb,
	priority_score bigint
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $function$
WITH lifecycle_order AS (
	SELECT bucket, COALESCE(MAX(ordinal), 500) AS ordinal
	  FROM profile_lifecycle_rule
	 WHERE profile_id = profile_id_arg
	 GROUP BY bucket
),
ranked AS (
	SELECT ''::text AS call_id,
	       ''::text AS title,
	       c.started_at,
	       c.duration_seconds,
	       c.system,
	       c.direction,
	       c.scope,
	       c.lifecycle_bucket AS bucket,
	       c.lifecycle_confidence AS confidence,
	       c.lifecycle_reason AS reason,
	       c.evidence_fields_json,
	       (
	         (100 - COALESCE(lo.ordinal, 500))
	         + CASE WHEN c.lifecycle_bucket IN ('closed_won', 'closed_lost', 'post_sales') THEN 50 ELSE 0 END
	         + CASE WHEN c.lifecycle_confidence = 'high' THEN 20 ELSE 0 END
	         + CASE WHEN c.scope = 'External' THEN 25 ELSE 0 END
	         + CASE WHEN c.direction = 'Conference' THEN 20 ELSE 0 END
	         + CASE WHEN c.duration_seconds >= 1800 THEN 20 WHEN c.duration_seconds >= 600 THEN 10 ELSE 0 END
	         + CASE WHEN c.deal_count > 0 THEN 10 ELSE 0 END
	         - CASE WHEN c.duration_seconds > 0 AND c.duration_seconds < 300 AND c.direction <> 'Conference' THEN 20 ELSE 0 END
	       )::bigint AS priority_score
	  FROM profile_call_fact_cache c
	  JOIN profile_meta p
	    ON p.id = c.profile_id
	  LEFT JOIN lifecycle_order lo
	    ON lo.bucket = c.lifecycle_bucket
	 WHERE p.is_active = true
	   AND c.profile_id = profile_id_arg
	   AND (canonical_sha_arg = '' OR c.canonical_sha256 = canonical_sha_arg)
	   AND NOT c.transcript_present
	   AND (bucket_arg = '' OR c.lifecycle_bucket = bucket_arg)
	   AND (from_date_arg = '' OR c.started_at >= from_date_arg)
	   AND (to_date_arg = '' OR c.started_at < ((NULLIF(to_date_arg, '')::date + INTERVAL '1 day')::date::text))
	   AND (scope_arg = '' OR c.scope = scope_arg)
	   AND (system_arg = '' OR c.system = system_arg)
	   AND (direction_arg = '' OR c.direction = direction_arg)
)
SELECT call_id, title, started_at, duration_seconds, system, direction, scope,
       bucket, confidence, reason, evidence_fields_json, priority_score
  FROM ranked
 ORDER BY priority_score DESC, started_at DESC, call_id
 LIMIT LEAST(GREATEST(COALESCE(row_limit, 25), 1), 1000)
$function$;
REVOKE ALL ON FUNCTION gongmcp_profile_transcript_backlog_sanitized(bigint, text, text, text, text, text, text, text, integer) FROM PUBLIC;
`,
	`
ALTER TABLE call_facts ADD COLUMN IF NOT EXISTS participant_title_present BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE call_facts ADD COLUMN IF NOT EXISTS loss_reason_present BOOLEAN NOT NULL DEFAULT false;
CREATE INDEX IF NOT EXISTS idx_pg_call_facts_participant_title_present ON call_facts(participant_title_present, call_date, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_pg_call_facts_loss_reason_present ON call_facts(loss_reason_present, call_date, started_at DESC);
` + postgresBusinessAnalysisFunctionsSQL + postgresBusinessAnalysisReaderGrantsSQL + `
`,
	`
CREATE TABLE IF NOT EXISTS governance_ingest_skipped_calls (
	call_id TEXT PRIMARY KEY,
	config_sha256 TEXT NOT NULL,
	matched_list TEXT NOT NULL,
	source_category TEXT NOT NULL,
	run_id BIGINT,
	skipped_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_pg_governance_ingest_skipped_calls_config
	ON governance_ingest_skipped_calls(config_sha256);
` + postgresMissingTranscriptsFunctionSQL + postgresMissingTranscriptCountFunctionSQL + `
`,
}
