package postgres

var migrations = []string{
	`
CREATE TABLE IF NOT EXISTS gongctl_schema_migrations (
	version INTEGER PRIMARY KEY,
	applied_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sync_runs (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	scope TEXT NOT NULL,
	sync_key TEXT NOT NULL DEFAULT '',
	cursor TEXT NOT NULL DEFAULT '',
	from_value TEXT NOT NULL DEFAULT '',
	to_value TEXT NOT NULL DEFAULT '',
	request_context TEXT NOT NULL DEFAULT '',
	status TEXT NOT NULL,
	started_at TEXT NOT NULL,
	finished_at TEXT,
	records_seen BIGINT NOT NULL DEFAULT 0,
	records_written BIGINT NOT NULL DEFAULT 0,
	error_text TEXT NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_pg_sync_runs_scope_started_at ON sync_runs(scope, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_pg_sync_runs_status ON sync_runs(status);

CREATE TABLE IF NOT EXISTS sync_state (
	sync_key TEXT PRIMARY KEY,
	scope TEXT NOT NULL,
	cursor TEXT NOT NULL DEFAULT '',
	last_run_id BIGINT,
	last_status TEXT NOT NULL,
	last_error TEXT NOT NULL DEFAULT '',
	last_success_at TEXT,
	updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_pg_sync_state_scope ON sync_state(scope);

CREATE TABLE IF NOT EXISTS calls (
	call_id TEXT PRIMARY KEY,
	title TEXT NOT NULL DEFAULT '',
	started_at TEXT NOT NULL DEFAULT '',
	duration_seconds BIGINT NOT NULL DEFAULT 0,
	parties_count BIGINT NOT NULL DEFAULT 0,
	context_present BOOLEAN NOT NULL DEFAULT false,
	raw_json JSONB NOT NULL,
	raw_sha256 TEXT NOT NULL,
	first_seen_at TEXT NOT NULL,
	updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_pg_calls_started_at ON calls(started_at DESC);

CREATE TABLE IF NOT EXISTS users (
	user_id TEXT PRIMARY KEY,
	email TEXT NOT NULL DEFAULT '',
	first_name TEXT NOT NULL DEFAULT '',
	last_name TEXT NOT NULL DEFAULT '',
	display_name TEXT NOT NULL DEFAULT '',
	title TEXT NOT NULL DEFAULT '',
	active BOOLEAN NOT NULL DEFAULT false,
	raw_json JSONB NOT NULL,
	raw_sha256 TEXT NOT NULL,
	first_seen_at TEXT NOT NULL,
	updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_pg_users_email ON users(email);

CREATE TABLE IF NOT EXISTS transcripts (
	call_id TEXT PRIMARY KEY,
	raw_json JSONB NOT NULL,
	raw_sha256 TEXT NOT NULL,
	segment_count INTEGER NOT NULL DEFAULT 0,
	first_seen_at TEXT NOT NULL,
	updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS transcript_segments (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	call_id TEXT NOT NULL,
	segment_index INTEGER NOT NULL,
	speaker_id TEXT NOT NULL DEFAULT '',
	start_ms BIGINT NOT NULL DEFAULT 0,
	end_ms BIGINT NOT NULL DEFAULT 0,
	text TEXT NOT NULL,
	raw_json JSONB NOT NULL,
	search_vector TSVECTOR GENERATED ALWAYS AS (to_tsvector('simple', coalesce(text, ''))) STORED,
	UNIQUE(call_id, segment_index)
);

CREATE INDEX IF NOT EXISTS idx_pg_transcript_segments_call_id ON transcript_segments(call_id, segment_index);
CREATE INDEX IF NOT EXISTS idx_pg_transcript_segments_search ON transcript_segments USING GIN(search_vector);
`,
}
