package postgres

import (
	"fmt"
	"sort"
	"strings"
)

type ScopedReaderGrantSQLParams struct {
	Allowlist    []string
	RoleName     string
	DatabaseName string
	Generator    string
}

func ReadOnlyOptionsForToolAllowlist(allowlist []string) ReadOnlyOptions {
	signatures := FunctionSignaturesForTools(allowlist)
	options := ReadOnlyOptions{
		RequiredFunctionSignatures:     signatures,
		AllowedFunctionSignatures:      signatures,
		EnforceAllowedFunctionBoundary: true,
	}
	if isReviewedScopedReaderSurface(allowlist) {
		signatures = scopedReaderFunctionSignatures(signatures)
		options.RequiredFunctionSignatures = signatures
		options.AllowedFunctionSignatures = signatures
		columns := ScopedReaderColumnSelectGrants()
		options.RequiredColumnSelectGrants = columns
		options.AllowedColumnSelectGrants = columns
		options.EnforceAllowedColumnBoundary = true
	}
	return options
}

func BuildScopedReaderGrantSQL(params ScopedReaderGrantSQLParams) (string, error) {
	options := ReadOnlyOptionsForToolAllowlist(params.Allowlist)
	if !options.EnforceAllowedColumnBoundary || !isReviewedScopedReaderSurface(params.Allowlist) {
		return "", fmt.Errorf("scoped reader grant SQL currently supports only reviewed business-pilot and analyst scoped reader surfaces")
	}
	roleIdent, err := quotePostgresIdentifier(params.RoleName)
	if err != nil {
		return "", fmt.Errorf("invalid role name: %w", err)
	}
	dbIdent, err := quotePostgresIdentifier(params.DatabaseName)
	if err != nil {
		return "", fmt.Errorf("invalid database name: %w", err)
	}

	var b strings.Builder
	generator := strings.TrimSpace(params.Generator)
	if generator == "" {
		generator = "gongctl/gongmcp scoped-reader grant helper"
	}
	b.WriteString("-- Generated by ")
	b.WriteString(generator)
	b.WriteString(".\n")
	b.WriteString("-- Role and credentials must already exist; create and rotate passwords outside this grant block using your secret manager.\n")
	b.WriteString("-- This block reconciles reviewed grants for the named role by clearing existing public table/function/sequence privileges before regranting the selected surface.\n")
	b.WriteString("-- It reconciles current public objects only; gongmcp startup rejects default privileges that would grant future public objects to this service role.\n")
	b.WriteString("-- Use a standalone LOGIN NOINHERIT role with no role memberships; the apply command rejects roles that inherit from or are granted to other roles.\n")
	b.WriteString("-- This is a gongmcp service credential, not an analyst SQL login; selected functions still expose minimized operational metadata, counts, timings, and tenant terminology.\n")
	b.WriteString("-- Direct SQL callers can invoke capped sanitized profile-cache rows, sanitized profile summaries, and sanitized analyst business-analysis wrappers; MCP limits are still enforced above SQL helpers.\n")
	b.WriteString("-- This grant block supports reviewed business-pilot and analyst scoped readers for Postgres service credentials; use compatibility roles only for operator-only migration/debug sessions.\n")
	b.WriteString("-- Role expected before running this block: ")
	b.WriteString(roleIdent)
	b.WriteString("\n")
	b.WriteString("BEGIN;\n")
	b.WriteString("REVOKE CREATE ON SCHEMA \"public\" FROM PUBLIC;\n")
	b.WriteString("REVOKE CREATE ON SCHEMA \"public\" FROM ")
	b.WriteString(roleIdent)
	b.WriteString(";\n")
	b.WriteString("GRANT CONNECT ON DATABASE ")
	b.WriteString(dbIdent)
	b.WriteString(" TO ")
	b.WriteString(roleIdent)
	b.WriteString(";\n")
	b.WriteString("GRANT USAGE ON SCHEMA \"public\" TO ")
	b.WriteString(roleIdent)
	b.WriteString(";\n")
	b.WriteString("REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA \"public\" FROM ")
	b.WriteString(roleIdent)
	b.WriteString(";\n")
	b.WriteString("REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA \"public\" FROM ")
	b.WriteString(roleIdent)
	b.WriteString(";\n")
	b.WriteString("REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA \"public\" FROM ")
	b.WriteString(roleIdent)
	b.WriteString(";\n")
	b.WriteString("DO $gongctl_scoped_reader_reconcile$\n")
	b.WriteString("DECLARE\n")
	b.WriteString("  target_role text := ")
	b.WriteString(quotePostgresLiteral(params.RoleName))
	b.WriteString(";\n")
	b.WriteString("  target_function regprocedure;\n")
	b.WriteString("  target_column record;\n")
	b.WriteString("BEGIN\n")
	b.WriteString("  FOR target_function IN\n")
	b.WriteString("    SELECT p.oid::regprocedure\n")
	b.WriteString("      FROM pg_proc p\n")
	b.WriteString("      JOIN pg_namespace n ON n.oid = p.pronamespace\n")
	b.WriteString("     WHERE n.nspname = 'public'\n")
	b.WriteString("       AND p.proname LIKE 'gongmcp_%'\n")
	b.WriteString("  LOOP\n")
	b.WriteString("    EXECUTE format('REVOKE EXECUTE ON FUNCTION %s FROM %I', target_function::text, target_role);\n")
	b.WriteString("  END LOOP;\n")
	b.WriteString("  FOR target_column IN\n")
	b.WriteString("    SELECT table_schema, table_name, column_name\n")
	b.WriteString("      FROM information_schema.columns\n")
	b.WriteString("     WHERE table_schema = 'public'\n")
	b.WriteString("  LOOP\n")
	b.WriteString("    EXECUTE format('REVOKE SELECT (%I) ON TABLE %I.%I FROM %I', target_column.column_name, target_column.table_schema, target_column.table_name, target_role);\n")
	b.WriteString("  END LOOP;\n")
	b.WriteString("END\n")
	b.WriteString("$gongctl_scoped_reader_reconcile$;\n")
	for _, signature := range rawScopedReaderFunctionRevokes() {
		b.WriteString("REVOKE EXECUTE ON FUNCTION ")
		b.WriteString(signature)
		b.WriteString(" FROM ")
		b.WriteString(roleIdent)
		b.WriteString(";\n")
	}

	for _, grant := range groupedColumnGrants(options.RequiredColumnSelectGrants) {
		b.WriteString("GRANT SELECT (")
		for i, column := range grant.Columns {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(column)
		}
		b.WriteString(") ON TABLE public.")
		b.WriteString(grant.Table)
		b.WriteString(" TO ")
		b.WriteString(roleIdent)
		b.WriteString(";\n")
	}
	signatures := dedupeStrings(options.RequiredFunctionSignatures)
	sort.Strings(signatures)
	for _, signature := range signatures {
		b.WriteString("GRANT EXECUTE ON FUNCTION ")
		b.WriteString(signature)
		b.WriteString(" TO ")
		b.WriteString(roleIdent)
		b.WriteString(";\n")
	}
	b.WriteString("COMMIT;\n")
	return b.String(), nil
}

func GovernanceFunctionSignatures() []string {
	return []string{
		"public.gongmcp_governance_data_fingerprint()",
		"public.gongmcp_governance_policy_state(text)",
		"public.gongmcp_governance_suppressed_call_ids(text)",
	}
}

func FunctionSignaturesForTools(allowlist []string) []string {
	profileReadinessFunctions := []string{
		"public.gongmcp_active_business_profile()",
		"public.gongmcp_profile_call_fact_cache_meta(bigint, text)",
		"public.gongmcp_profile_data_fingerprint()",
	}
	profileRowsFunctions := append(copyPostgresFunctionSignatures(profileReadinessFunctions),
		"public.gongmcp_profile_call_fact_cache(bigint, text)",
	)
	profileSummaryFunctions := append(copyPostgresFunctionSignatures(profileReadinessFunctions),
		"public.gongmcp_profile_call_fact_summary(bigint, text, text, text, text, text, text, text, integer)",
	)
	businessAnalysisCoreFunctions := []string{
		"public.gongmcp_business_analysis_calls(text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, integer)",
		"public.gongmcp_business_analysis_summary(text, text, text, text, text, text, text, text, text, text, text, text, text, text, text)",
	}
	businessAnalysisEvidenceFunctions := append(copyPostgresFunctionSignatures(businessAnalysisCoreFunctions),
		"public.gongmcp_business_analysis_evidence(text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, integer)",
	)
	businessAnalysisThemeDiscoveryFunctions := append(copyPostgresFunctionSignatures(businessAnalysisEvidenceFunctions),
		"public.gongmcp_business_analysis_theme_seed_sample(text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, integer)",
	)
	businessAnalysisDimensionFunctions := append(copyPostgresFunctionSignatures(businessAnalysisCoreFunctions),
		"public.gongmcp_business_analysis_dimension(text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, integer)",
	)
	functionsByTool := map[string][]string{
		"analyze_late_stage_crm_signals": {
			"public.gongmcp_late_stage_call_counts(text, text, text)",
			"public.gongmcp_late_stage_stage_counts(text, text, text)",
			"public.gongmcp_late_stage_signal_inventory(text, text, text, integer, boolean)",
		},
		"build_call_cohort":    businessAnalysisCoreFunctions,
		"build_quote_pack":     businessAnalysisEvidenceFunctions,
		"build_theme_brief":    businessAnalysisEvidenceFunctions,
		"compare_call_cohorts": businessAnalysisCoreFunctions,
		"compare_lifecycle_crm_fields": {
			"public.gongmcp_compare_lifecycle_crm_fields(text, text, text, integer)",
		},
		"compare_theme_outcomes":          businessAnalysisDimensionFunctions,
		"compare_themes_by_segment":       businessAnalysisDimensionFunctions,
		"compare_themes_over_time":        businessAnalysisDimensionFunctions,
		"compare_won_lost_theme_patterns": businessAnalysisDimensionFunctions,
		"crm_field_population_matrix": {
			"public.gongmcp_crm_field_population_matrix(text, text, integer)",
		},
		"diagnose_attribution_coverage":     businessAnalysisCoreFunctions,
		"discover_themes_in_cohort":         businessAnalysisThemeDiscoveryFunctions,
		"explain_analysis_limitations":      businessAnalysisCoreFunctions,
		"extract_theme_quotes":              businessAnalysisEvidenceFunctions,
		"generate_outreach_sequence_inputs": businessAnalysisEvidenceFunctions,
		"generate_sales_hooks_from_themes":  businessAnalysisEvidenceFunctions,
		"get_sync_status": {
			"public.gongmcp_active_business_profile()",
			"public.gongmcp_missing_transcript_count()",
			"public.gongmcp_profile_call_fact_cache_meta(bigint, text)",
			"public.gongmcp_profile_data_fingerprint()",
			"public.gongmcp_scorecard_activity_totals()",
		},
		"get_business_profile": {
			"public.gongmcp_active_business_profile()",
		},
		"get_scorecard": {
			"public.gongmcp_scorecard_detail(text)",
		},
		"inspect_call_cohort": businessAnalysisCoreFunctions,
		"list_call_cohorts":   {},
		"list_business_concepts": {
			"public.gongmcp_active_business_profile()",
		},
		"list_crm_object_types": {
			"public.gongmcp_crm_object_type_summary()",
		},
		"list_call_ai_highlights": {
			"public.gongmcp_list_call_ai_highlights(text, integer)",
		},
		"list_crm_fields": {
			"public.gongmcp_crm_field_summary_sanitized(text, integer)",
		},
		"list_lifecycle_buckets": profileReadinessFunctions,
		"list_scorecards": {
			"public.gongmcp_scorecards(boolean, integer)",
		},
		"list_unmapped_crm_fields": append([]string{
			"public.gongmcp_unmapped_crm_field_inventory(integer)",
		}, profileReadinessFunctions...),
		"missing_transcripts": {
			"public.gongmcp_missing_transcript_count()",
			"public.gongmcp_missing_transcripts(text, text, text, text, text, text, text, text, integer)",
		},
		"opportunities_missing_transcripts": {
			"public.gongmcp_opportunities_missing_transcripts(text, integer)",
		},
		"opportunity_call_summary": {
			"public.gongmcp_opportunity_call_summary(text, integer)",
		},
		"prioritize_transcripts_by_lifecycle":      profileRowsFunctions,
		"rank_personas_by_insight_quality":         businessAnalysisDimensionFunctions,
		"rank_quotes_for_sales_use":                businessAnalysisEvidenceFunctions,
		"rank_transcript_backlog":                  profileRowsFunctions,
		"recommend_target_personas_and_industries": businessAnalysisEvidenceFunctions,
		"score_cohort_evidence_quality":            businessAnalysisCoreFunctions,
		"search_calls_by_filters":                  businessAnalysisCoreFunctions,
		"search_calls_by_lifecycle":                profileRowsFunctions,
		"search_crm_field_values": {
			"public.gongmcp_crm_field_value_search(text, text, text, integer, boolean, boolean)",
		},
		"search_quotes_in_cohort": businessAnalysisEvidenceFunctions,
		"search_transcript_quotes_with_attribution": {
			"public.gongmcp_search_transcript_quotes_with_attribution(text, text, text, text, text, text, text, text, text, text, text, integer)",
		},
		"search_transcript_segments": {
			"public.gongmcp_search_transcript_segments(text, integer)",
			"public.gongmcp_search_transcript_segments_by_call_facts(text, text, text, text, text, text, text, integer)",
		},
		"search_transcripts_by_call_facts": {
			"public.gongmcp_search_transcript_segments_by_call_facts(text, text, text, text, text, text, text, integer)",
		},
		"search_transcripts_by_crm_context": {
			"public.gongmcp_search_transcript_segments_by_crm_context(text, text, text, integer)",
		},
		"search_transcripts_by_filters":           businessAnalysisEvidenceFunctions,
		"suggest_filter_refinements":              businessAnalysisCoreFunctions,
		"summarize_call_facts":                    profileSummaryFunctions,
		"summarize_loss_reasons_by_theme":         businessAnalysisDimensionFunctions,
		"summarize_pipeline_progression_by_theme": businessAnalysisDimensionFunctions,
		"summarize_calls_by_filters":              businessAnalysisDimensionFunctions,
		"summarize_calls_by_lifecycle":            profileRowsFunctions,
		"summarize_scorecard_activity": {
			"public.gongmcp_scorecard_activity_summary(text, integer)",
			"public.gongmcp_scorecard_activity_totals()",
		},
		"summarize_themes_by_dimension": businessAnalysisDimensionFunctions,
		"summarize_themes_by_industry":  businessAnalysisDimensionFunctions,
		"summarize_themes_by_persona":   businessAnalysisDimensionFunctions,
	}
	var signatures []string
	for _, name := range allowlist {
		signatures = append(signatures, functionsByTool[name]...)
	}
	return signatures
}

func scopedReaderFunctionSignatures(signatures []string) []string {
	out := make([]string, 0, len(signatures))
	for _, signature := range signatures {
		if signature == "public.gongmcp_profile_call_fact_cache(bigint, text)" {
			out = append(out,
				"public.gongmcp_profile_call_fact_cache_sanitized_limited(bigint, text, integer)",
				"public.gongmcp_profile_lifecycle_summary_sanitized(bigint, text, text)",
				"public.gongmcp_profile_transcript_backlog_sanitized(bigint, text, text, text, text, text, text, text, integer)",
			)
			continue
		}
		if signature == "public.gongmcp_profile_call_fact_cache_meta(bigint, text)" {
			signature = "public.gongmcp_profile_call_fact_cache_meta_sanitized(bigint)"
		}
		if signature == "public.gongmcp_profile_call_fact_summary(bigint, text, text, text, text, text, text, text, integer)" {
			signature = "public.gongmcp_profile_call_fact_summary_sanitized(bigint, text, text, text, text, text, text, text, integer)"
		}
		if signature == "public.gongmcp_active_business_profile()" {
			signature = "public.gongmcp_active_business_profile_sanitized()"
		}
		if signature == "public.gongmcp_search_transcript_quotes_with_attribution(text, text, text, text, text, text, text, text, text, text, text, integer)" {
			signature = "public.gongmcp_search_transcript_quotes_with_attribution_sanitized(text, text, text, text, text, text, text, text, text, text, text, integer)"
		}
		if signature == "public.gongmcp_business_analysis_calls(text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, integer)" {
			signature = "public.gongmcp_business_analysis_calls_sanitized(text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, integer)"
		}
		if signature == "public.gongmcp_business_analysis_evidence(text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, integer)" {
			signature = "public.gongmcp_business_analysis_evidence_sanitized(text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, integer)"
		}
		if signature == "public.gongmcp_business_analysis_theme_seed_sample(text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, integer)" {
			signature = "public.gongmcp_business_analysis_theme_seed_sample_sanitized(text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, integer)"
		}
		if signature == "public.gongmcp_search_transcript_segments(text, integer)" {
			signature = "public.gongmcp_search_transcript_segments_sanitized(text, integer)"
		}
		if signature == "public.gongmcp_search_transcript_segments_by_call_facts(text, text, text, text, text, text, text, integer)" {
			signature = "public.gongmcp_search_transcript_segments_by_call_facts_sanitized(text, text, text, text, text, text, text, integer)"
		}
		out = append(out, signature)
	}
	return out
}

func isReviewedScopedReaderSurface(allowlist []string) bool {
	return BusinessPilotScopedColumns(allowlist) || AnalystScopedColumns(allowlist)
}

func BusinessPilotScopedColumns(allowlist []string) bool {
	want := map[string]struct{}{
		"get_sync_status":              {},
		"summarize_call_facts":         {},
		"summarize_calls_by_lifecycle": {},
		"rank_transcript_backlog":      {},
	}
	if len(allowlist) != len(want) {
		return false
	}
	for _, name := range allowlist {
		if _, ok := want[name]; !ok {
			return false
		}
	}
	return true
}

func AnalystScopedColumns(allowlist []string) bool {
	want := map[string]struct{}{
		"analyze_late_stage_crm_signals":            {},
		"build_call_cohort":                         {},
		"build_quote_pack":                          {},
		"build_theme_brief":                         {},
		"compare_call_cohorts":                      {},
		"compare_lifecycle_crm_fields":              {},
		"compare_theme_outcomes":                    {},
		"compare_themes_by_segment":                 {},
		"compare_themes_over_time":                  {},
		"compare_won_lost_theme_patterns":           {},
		"crm_field_population_matrix":               {},
		"diagnose_attribution_coverage":             {},
		"discover_themes_in_cohort":                 {},
		"explain_analysis_limitations":              {},
		"extract_theme_quotes":                      {},
		"generate_outreach_sequence_inputs":         {},
		"generate_sales_hooks_from_themes":          {},
		"get_business_profile":                      {},
		"get_sync_status":                           {},
		"inspect_call_cohort":                       {},
		"list_business_concepts":                    {},
		"list_call_ai_highlights":                   {},
		"list_call_cohorts":                         {},
		"list_crm_fields":                           {},
		"list_crm_object_types":                     {},
		"list_lifecycle_buckets":                    {},
		"list_unmapped_crm_fields":                  {},
		"opportunities_missing_transcripts":         {},
		"opportunity_call_summary":                  {},
		"prioritize_transcripts_by_lifecycle":       {},
		"rank_personas_by_insight_quality":          {},
		"rank_quotes_for_sales_use":                 {},
		"rank_transcript_backlog":                   {},
		"recommend_target_personas_and_industries":  {},
		"score_cohort_evidence_quality":             {},
		"search_calls_by_filters":                   {},
		"search_quotes_in_cohort":                   {},
		"search_transcript_quotes_with_attribution": {},
		"search_transcript_segments":                {},
		"search_transcripts_by_call_facts":          {},
		"search_transcripts_by_crm_context":         {},
		"search_transcripts_by_filters":             {},
		"suggest_filter_refinements":                {},
		"summarize_call_facts":                      {},
		"summarize_calls_by_filters":                {},
		"summarize_calls_by_lifecycle":              {},
		"summarize_loss_reasons_by_theme":           {},
		"summarize_pipeline_progression_by_theme":   {},
		"summarize_themes_by_dimension":             {},
		"summarize_themes_by_industry":              {},
		"summarize_themes_by_persona":               {},
	}
	if len(allowlist) != len(want) {
		return false
	}
	for _, name := range allowlist {
		if _, ok := want[name]; !ok {
			return false
		}
	}
	return true
}

func ScopedReaderColumnSelectGrants() []ColumnSelectGrant {
	grants := []ColumnSelectGrant{
		{Table: "gongctl_schema_migrations", Column: "version"},
		{Table: "calls", Column: "started_at"},
		{Table: "calls", Column: "parties_count"},
		{Table: "calls", Column: "context_present"},
		{Table: "users", Column: "user_id"},
		{Table: "users", Column: "title"},
		{Table: "transcripts", Column: "segment_count"},
		{Table: "gongmcp_call_context_objects", Column: "id"},
		{Table: "gongmcp_call_context_objects", Column: "object_type"},
		{Table: "gongmcp_call_context_fields", Column: "id"},
		{Table: "gongmcp_call_context_fields", Column: "field_name"},
		{Table: "gongmcp_call_context_fields", Column: "field_label"},
		{Table: "gongmcp_call_context_fields", Column: "field_type"},
		{Table: "gongmcp_call_context_fields", Column: "field_populated"},
		{Table: "crm_integrations", Column: "integration_id"},
		{Table: "crm_schema_objects", Column: "object_type"},
		{Table: "crm_schema_fields", Column: "field_name"},
		{Table: "gong_settings", Column: "kind"},
		{Table: "call_facts", Column: "lifecycle_bucket"},
		{Table: "call_facts", Column: "transcript_present"},
		{Table: "call_facts", Column: "transcript_status"},
		{Table: "call_facts", Column: "duration_seconds"},
		{Table: "call_facts", Column: "started_at"},
		{Table: "call_facts", Column: "lifecycle_confidence"},
		{Table: "call_facts", Column: "opportunity_count"},
		{Table: "call_facts", Column: "account_count"},
		{Table: "postgres_read_model_state", Column: "model_name"},
		{Table: "postgres_read_model_state", Column: "model_version"},
		{Table: "postgres_read_model_state", Column: "rebuilt_at"},
		{Table: "postgres_read_model_state", Column: "call_count"},
		{Table: "postgres_read_model_state", Column: "fact_count"},
		{Table: "postgres_read_model_state", Column: "missing_fact_call_count"},
		{Table: "postgres_read_model_state", Column: "orphan_fact_count"},
		{Table: "postgres_read_model_state", Column: "stale_reason"},
		{Table: "postgres_read_model_state", Column: "updated_at"},
	}
	for _, column := range []string{"id", "scope", "sync_key", "cursor", "from_value", "to_value", "request_context", "status", "started_at", "finished_at", "records_seen", "records_written", "error_text"} {
		grants = append(grants, ColumnSelectGrant{Table: "gongmcp_sync_runs", Column: column})
	}
	for _, column := range []string{"sync_key", "scope", "cursor", "last_run_id", "last_status", "last_error", "last_success_at", "updated_at"} {
		grants = append(grants, ColumnSelectGrant{Table: "gongmcp_sync_state", Column: column})
	}
	return grants
}

func BusinessPilotColumnSelectGrants() []ColumnSelectGrant {
	return ScopedReaderColumnSelectGrants()
}

func rawScopedReaderFunctionRevokes() []string {
	return []string{
		"public.gongmcp_active_business_profile()",
		"public.gongmcp_profile_call_fact_cache(bigint, text)",
		"public.gongmcp_profile_call_fact_cache_meta(bigint, text)",
		"public.gongmcp_profile_call_fact_cache_sanitized(bigint, text)",
		"public.gongmcp_profile_call_fact_summary(bigint, text, text, text, text, text, text, text, integer)",
		"public.gongmcp_search_transcript_quotes_with_attribution(text, text, text, text, text, text, text, text, text, text, text, integer)",
		"public.gongmcp_business_analysis_calls(text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, integer)",
		"public.gongmcp_business_analysis_evidence(text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, integer)",
		"public.gongmcp_business_analysis_theme_seed_sample(text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, integer)",
		"public.gongmcp_search_transcript_segments(text, integer)",
		"public.gongmcp_search_transcript_segments_by_call_facts(text, text, text, text, text, text, text, integer)",
	}
}

func copyPostgresFunctionSignatures(signatures []string) []string {
	out := make([]string, len(signatures))
	copy(out, signatures)
	return out
}

func dedupeStrings(values []string) []string {
	seen := make(map[string]struct{}, len(values))
	out := make([]string, 0, len(values))
	for _, value := range values {
		if _, ok := seen[value]; ok {
			continue
		}
		seen[value] = struct{}{}
		out = append(out, value)
	}
	return out
}

type groupedPostgresColumnGrant struct {
	Table   string
	Columns []string
}

func groupedColumnGrants(grants []ColumnSelectGrant) []groupedPostgresColumnGrant {
	byTable := make(map[string][]string)
	for _, grant := range grants {
		table, err := quotePostgresIdentifier(grant.Table)
		if err != nil {
			panic(fmt.Sprintf("invalid built-in postgres grant table %q: %v", grant.Table, err))
		}
		column, err := quotePostgresIdentifier(grant.Column)
		if err != nil {
			panic(fmt.Sprintf("invalid built-in postgres grant column %q: %v", grant.Column, err))
		}
		byTable[table] = append(byTable[table], column)
	}
	tables := make([]string, 0, len(byTable))
	for table := range byTable {
		tables = append(tables, table)
	}
	sort.Strings(tables)
	out := make([]groupedPostgresColumnGrant, 0, len(tables))
	for _, table := range tables {
		columns := byTable[table]
		sort.Strings(columns)
		out = append(out, groupedPostgresColumnGrant{Table: table, Columns: columns})
	}
	return out
}

func quotePostgresIdentifier(name string) (string, error) {
	trimmed := strings.TrimSpace(name)
	if trimmed == "" {
		return "", fmt.Errorf("identifier is empty")
	}
	if len(trimmed) > 63 {
		return "", fmt.Errorf("identifier is longer than 63 bytes")
	}
	for i, r := range trimmed {
		if r > 127 {
			return "", fmt.Errorf("identifier must use ASCII letters, digits, or underscore")
		}
		if i == 0 {
			if (r < 'A' || r > 'Z') && (r < 'a' || r > 'z') && r != '_' {
				return "", fmt.Errorf("identifier must start with a letter or underscore")
			}
			continue
		}
		if (r < 'A' || r > 'Z') && (r < 'a' || r > 'z') && (r < '0' || r > '9') && r != '_' {
			return "", fmt.Errorf("identifier must use ASCII letters, digits, or underscore")
		}
	}
	return `"` + trimmed + `"`, nil
}

func quotePostgresLiteral(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "''") + "'"
}
