package postgres

import (
	"strings"
	"testing"

	"github.com/fyne-coder/gongcli_mcp/internal/mcp"
)

func TestBuildScopedReaderGrantSQLBusinessPilot(t *testing.T) {
	allowlist := []string{"get_sync_status", "summarize_call_facts", "summarize_calls_by_lifecycle", "rank_transcript_backlog"}
	sql, err := BuildScopedReaderGrantSQL(ScopedReaderGrantSQLParams{
		Allowlist:    allowlist,
		RoleName:     "gongmcp_business_pilot_reader",
		DatabaseName: "gongctl",
	})
	if err != nil {
		t.Fatalf("BuildScopedReaderGrantSQL returned error: %v", err)
	}
	for _, want := range []string{
		`-- Generated by gongctl/gongmcp scoped-reader grant helper.`,
		`-- Role and credentials must already exist; create and rotate passwords outside this grant block using your secret manager.`,
		`-- This block reconciles reviewed grants for the named role by clearing existing public table/function/sequence privileges before regranting the selected surface.`,
		`-- It reconciles current public objects only; gongmcp startup rejects default privileges that would grant future public objects to this service role.`,
		`REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA "public" FROM "gongmcp_business_pilot_reader";`,
		`REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA "public" FROM "gongmcp_business_pilot_reader";`,
		`-- This is a gongmcp service credential, not an analyst SQL login; selected functions still expose minimized operational metadata, counts, timings, and tenant terminology.`,
		`-- Direct SQL callers can invoke capped sanitized profile-cache rows, sanitized profile summaries, and sanitized analyst business-analysis wrappers; MCP limits are still enforced above SQL helpers.`,
		`-- This grant block supports reviewed business-workbench/facade, business-pilot, analyst, and redacted-all-readonly scoped readers for Postgres service credentials; use compatibility roles only for operator-only migration/debug sessions.`,
		`GRANT CONNECT ON DATABASE "gongctl" TO "gongmcp_business_pilot_reader";`,
		`REVOKE CREATE ON SCHEMA "public" FROM PUBLIC;`,
		`GRANT USAGE ON SCHEMA "public" TO "gongmcp_business_pilot_reader";`,
		`REVOKE EXECUTE ON FUNCTION public.gongmcp_active_business_profile() FROM "gongmcp_business_pilot_reader";`,
		`REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA "public" FROM "gongmcp_business_pilot_reader";`,
		`REVOKE EXECUTE ON FUNCTION public.gongmcp_profile_call_fact_cache(bigint, text) FROM "gongmcp_business_pilot_reader";`,
		`REVOKE EXECUTE ON FUNCTION public.gongmcp_profile_call_fact_cache_sanitized(bigint, text) FROM "gongmcp_business_pilot_reader";`,
		`GRANT SELECT ("context_present", "parties_count", "started_at") ON TABLE public."calls" TO "gongmcp_business_pilot_reader";`,
		`GRANT SELECT ("account_count", "account_industry", "duration_seconds", "lifecycle_bucket", "lifecycle_confidence", "likely_voicemail_or_ivr", "opportunity_count", "opportunity_stage", "started_at", "transcript_present", "transcript_status") ON TABLE public."call_facts" TO "gongmcp_business_pilot_reader";`,
		`GRANT SELECT ("field_limit_exceeded", "last_error", "object_limit_exceeded") ON TABLE public."call_read_model_diagnostics" TO "gongmcp_business_pilot_reader";`,
		`GRANT SELECT ("active", "kind", "name", "object_id", "updated_at") ON TABLE public."gong_settings" TO "gongmcp_business_pilot_reader";`,
		`GRANT SELECT ("first_seen_at", "integration_id", "name", "provider", "updated_at") ON TABLE public."crm_integrations" TO "gongmcp_business_pilot_reader";`,
		`GRANT SELECT ("display_name", "field_count", "first_seen_at", "integration_id", "object_type", "updated_at") ON TABLE public."crm_schema_objects" TO "gongmcp_business_pilot_reader";`,
		`GRANT SELECT ("field_label", "field_name", "field_type", "first_seen_at", "integration_id", "object_type", "updated_at") ON TABLE public."crm_schema_fields" TO "gongmcp_business_pilot_reader";`,
		`GRANT EXECUTE ON FUNCTION public.gongmcp_active_business_profile_sanitized() TO "gongmcp_business_pilot_reader";`,
		`GRANT EXECUTE ON FUNCTION public.gongmcp_profile_call_fact_cache_meta_sanitized(bigint) TO "gongmcp_business_pilot_reader";`,
		`GRANT EXECUTE ON FUNCTION public.gongmcp_profile_call_fact_cache_sanitized_limited(bigint, text, integer) TO "gongmcp_business_pilot_reader";`,
		`GRANT EXECUTE ON FUNCTION public.gongmcp_profile_call_fact_summary_sanitized(bigint, text, text, text, text, text, text, text, integer) TO "gongmcp_business_pilot_reader";`,
		`GRANT EXECUTE ON FUNCTION public.gongmcp_profile_data_fingerprint() TO "gongmcp_business_pilot_reader";`,
		`GRANT EXECUTE ON FUNCTION public.gongmcp_profile_lifecycle_summary_sanitized(bigint, text, text) TO "gongmcp_business_pilot_reader";`,
		`GRANT EXECUTE ON FUNCTION public.gongmcp_profile_transcript_backlog_sanitized(bigint, text, text, text, text, text, text, text, integer) TO "gongmcp_business_pilot_reader";`,
		`GRANT EXECUTE ON FUNCTION public.gongmcp_missing_transcript_count() TO "gongmcp_business_pilot_reader";`,
		`COMMIT;`,
	} {
		if !strings.Contains(sql, want) {
			t.Fatalf("generated SQL missing %q\n%s", want, sql)
		}
	}
	for _, forbidden := range []string{
		`PASSWORD`,
		`CREATE ROLE`,
		`"call_id", "title"`,
		`"call_id"`,
		`"object_key"`,
		`GRANT EXECUTE ON FUNCTION public.gongmcp_active_business_profile()`,
		`GRANT EXECUTE ON FUNCTION public.gongmcp_profile_call_fact_cache(bigint, text)`,
		`GRANT EXECUTE ON FUNCTION public.gongmcp_profile_call_fact_cache_meta(bigint, text)`,
		`GRANT EXECUTE ON FUNCTION public.gongmcp_profile_call_fact_cache_sanitized(bigint, text)`,
		`GRANT EXECUTE ON FUNCTION public.gongmcp_profile_call_fact_summary(bigint, text, text, text, text, text, text, text, integer)`,
		`public.gongmcp_missing_transcripts`,
		`field_values_json`,
	} {
		if strings.Contains(sql, forbidden) {
			t.Fatalf("generated SQL included forbidden %q\n%s", forbidden, sql)
		}
	}
	for _, line := range strings.Split(sql, "\n") {
		if strings.Contains(line, `ON TABLE public."calls"`) && strings.Contains(line, `"call_id"`) {
			t.Fatalf("generated SQL included calls.call_id grant\n%s", sql)
		}
		if strings.Contains(line, `ON TABLE public."calls"`) && strings.Contains(line, `"title"`) {
			t.Fatalf("generated SQL included calls.title grant\n%s", sql)
		}
		if strings.Contains(line, `ON TABLE public."call_facts"`) && strings.Contains(line, `"call_id"`) {
			t.Fatalf("generated SQL included call_facts.call_id grant\n%s", sql)
		}
		if strings.Contains(line, `ON TABLE public."call_facts"`) && strings.Contains(line, `"title"`) {
			t.Fatalf("generated SQL included call_facts.title grant\n%s", sql)
		}
	}
}

func TestBuildScopedReaderGrantSQLRejectsUnsupportedSurface(t *testing.T) {
	if _, err := BuildScopedReaderGrantSQL(ScopedReaderGrantSQLParams{
		Allowlist:    []string{"get_sync_status", "search_calls"},
		RoleName:     "gongmcp_reader",
		DatabaseName: "gongctl",
	}); err == nil {
		t.Fatal("BuildScopedReaderGrantSQL accepted unsupported non-business-pilot surface")
	}
}

func TestBuildScopedReaderGrantSQLAnalystUsesSanitizedBusinessAnalysisFunctions(t *testing.T) {
	allowlist := []string{
		"get_sync_status",
		"list_crm_object_types",
		"list_crm_fields",
		"get_business_profile",
		"list_business_concepts",
		"list_unmapped_crm_fields",
		"analyze_late_stage_crm_signals",
		"opportunities_missing_transcripts",
		"search_transcripts_by_crm_context",
		"opportunity_call_summary",
		"crm_field_population_matrix",
		"list_lifecycle_buckets",
		"summarize_calls_by_lifecycle",
		"prioritize_transcripts_by_lifecycle",
		"compare_lifecycle_crm_fields",
		"summarize_call_facts",
		"rank_transcript_backlog",
		"search_transcript_segments",
		"search_transcripts_by_call_facts",
		"search_transcript_quotes_with_attribution",
		"list_scorecards",
		"get_scorecard",
		"build_call_cohort",
		"inspect_call_cohort",
		"list_call_cohorts",
		"compare_call_cohorts",
		"search_calls_by_filters",
		"summarize_calls_by_filters",
		"search_transcripts_by_filters",
		"discover_themes_in_cohort",
		"summarize_themes_by_dimension",
		"compare_themes_over_time",
		"compare_themes_by_segment",
		"extract_theme_quotes",
		"search_quotes_in_cohort",
		"rank_quotes_for_sales_use",
		"build_quote_pack",
		"list_call_ai_highlights",
		"compare_theme_outcomes",
		"summarize_pipeline_progression_by_theme",
		"summarize_loss_reasons_by_theme",
		"compare_won_lost_theme_patterns",
		"summarize_themes_by_persona",
		"summarize_themes_by_industry",
		"rank_personas_by_insight_quality",
		"diagnose_attribution_coverage",
		"generate_sales_hooks_from_themes",
		"generate_outreach_sequence_inputs",
		"recommend_target_personas_and_industries",
		"build_theme_brief",
		"score_cohort_evidence_quality",
		"explain_analysis_limitations",
		"suggest_filter_refinements",
	}
	sql, err := BuildScopedReaderGrantSQL(ScopedReaderGrantSQLParams{
		Allowlist:    allowlist,
		RoleName:     "gongmcp_analyst_reader",
		DatabaseName: "gongctl",
	})
	if err != nil {
		t.Fatalf("BuildScopedReaderGrantSQL returned error: %v", err)
	}
	for _, want := range []string{
		`GRANT EXECUTE ON FUNCTION public.gongmcp_business_analysis_calls_sanitized(text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, boolean, integer, text) TO "gongmcp_analyst_reader";`,
		`GRANT EXECUTE ON FUNCTION public.gongmcp_business_analysis_evidence_sanitized(text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, boolean, integer, text) TO "gongmcp_analyst_reader";`,
		`GRANT EXECUTE ON FUNCTION public.gongmcp_business_analysis_theme_seed_sample_sanitized(text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, boolean, integer, text) TO "gongmcp_analyst_reader";`,
		`GRANT EXECUTE ON FUNCTION public.gongmcp_search_transcript_quotes_with_attribution_sanitized(text, text, text, text, text, text, text, text, text, text, text, integer) TO "gongmcp_analyst_reader";`,
		`GRANT EXECUTE ON FUNCTION public.gongmcp_search_transcript_segments_sanitized(text, integer) TO "gongmcp_analyst_reader";`,
		`GRANT EXECUTE ON FUNCTION public.gongmcp_search_transcript_segments_by_call_facts_sanitized(text, text, text, text, text, text, text, integer) TO "gongmcp_analyst_reader";`,
		`GRANT EXECUTE ON FUNCTION public.gongmcp_list_call_ai_highlights(text, integer) TO "gongmcp_analyst_reader";`,
		`GRANT EXECUTE ON FUNCTION public.gongmcp_business_analysis_dimension(text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, boolean, integer, text) TO "gongmcp_analyst_reader";`,
		`GRANT EXECUTE ON FUNCTION public.gongmcp_crm_field_summary_sanitized(text, integer) TO "gongmcp_analyst_reader";`,
	} {
		if !strings.Contains(sql, want) {
			t.Fatalf("generated SQL missing %q\n%s", want, sql)
		}
	}
	for _, forbidden := range []string{
		`GRANT EXECUTE ON FUNCTION public.gongmcp_business_analysis_calls(text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, boolean, integer, text)`,
		`GRANT EXECUTE ON FUNCTION public.gongmcp_business_analysis_evidence(text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, boolean, integer, text)`,
		`GRANT EXECUTE ON FUNCTION public.gongmcp_business_analysis_theme_seed_sample(text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, boolean, integer, text)`,
		`GRANT EXECUTE ON FUNCTION public.gongmcp_search_transcript_quotes_with_attribution(text, text, text, text, text, text, text, text, text, text, text, integer)`,
		`GRANT EXECUTE ON FUNCTION public.gongmcp_search_transcript_segments(text, integer)`,
		`GRANT EXECUTE ON FUNCTION public.gongmcp_search_transcript_segments_by_call_facts(text, text, text, text, text, text, text, integer)`,
		`GRANT SELECT ("highlight_text"`,
		`GRANT SELECT ("search_vector"`,
		`ON TABLE public."call_ai_highlights"`,
		`GRANT SELECT ("call_id"`,
	} {
		if strings.Contains(sql, forbidden) {
			t.Fatalf("generated SQL included forbidden %q\n%s", forbidden, sql)
		}
	}
}

func TestBuildScopedReaderGrantSQLAnalystExpansionGrantsScorecardInventory(t *testing.T) {
	allowlist := []string{
		"get_sync_status",
		"list_crm_object_types",
		"list_crm_fields",
		"get_business_profile",
		"list_business_concepts",
		"list_unmapped_crm_fields",
		"analyze_late_stage_crm_signals",
		"opportunities_missing_transcripts",
		"search_transcripts_by_crm_context",
		"opportunity_call_summary",
		"crm_field_population_matrix",
		"list_lifecycle_buckets",
		"summarize_calls_by_lifecycle",
		"prioritize_transcripts_by_lifecycle",
		"compare_lifecycle_crm_fields",
		"summarize_call_facts",
		"rank_transcript_backlog",
		"search_transcript_segments",
		"search_transcripts_by_call_facts",
		"search_transcript_quotes_with_attribution",
		"list_scorecards",
		"get_scorecard",
		"build_call_cohort",
		"inspect_call_cohort",
		"list_call_cohorts",
		"compare_call_cohorts",
		"search_calls_by_filters",
		"summarize_calls_by_filters",
		"search_transcripts_by_filters",
		"discover_themes_in_cohort",
		"summarize_themes_by_dimension",
		"compare_themes_over_time",
		"compare_themes_by_segment",
		"extract_theme_quotes",
		"search_quotes_in_cohort",
		"rank_quotes_for_sales_use",
		"build_quote_pack",
		"compare_theme_outcomes",
		"summarize_pipeline_progression_by_theme",
		"summarize_loss_reasons_by_theme",
		"compare_won_lost_theme_patterns",
		"summarize_themes_by_persona",
		"summarize_themes_by_industry",
		"rank_personas_by_insight_quality",
		"diagnose_attribution_coverage",
		"generate_sales_hooks_from_themes",
		"generate_outreach_sequence_inputs",
		"recommend_target_personas_and_industries",
		"build_theme_brief",
		"score_cohort_evidence_quality",
		"explain_analysis_limitations",
		"suggest_filter_refinements",
	}
	sql, err := BuildScopedReaderGrantSQL(ScopedReaderGrantSQLParams{
		Allowlist:    allowlist,
		RoleName:     "gongmcp_analyst_reader",
		DatabaseName: "gongctl",
	})
	if err != nil {
		t.Fatalf("BuildScopedReaderGrantSQL returned error: %v", err)
	}
	for _, want := range []string{
		`GRANT EXECUTE ON FUNCTION public.gongmcp_scorecards(boolean, integer) TO "gongmcp_analyst_reader";`,
		`GRANT EXECUTE ON FUNCTION public.gongmcp_scorecard_detail(text) TO "gongmcp_analyst_reader";`,
	} {
		if !strings.Contains(sql, want) {
			t.Fatalf("generated SQL missing %q\n%s", want, sql)
		}
	}
	for _, forbidden := range []string{
		`GRANT EXECUTE ON FUNCTION public.gongmcp_scorecard_activity_summary(text, integer) TO "gongmcp_analyst_reader";`,
	} {
		if strings.Contains(sql, forbidden) {
			t.Fatalf("generated SQL included forbidden activity helper %q\n%s", forbidden, sql)
		}
	}
}

func TestBuildScopedReaderGrantSQLRedactedAllReadonlyGrantsBroadSearchSurface(t *testing.T) {
	allowlist := mcp.PostgresRedactedAllReadonlyToolNames()
	sql, err := BuildScopedReaderGrantSQL(ScopedReaderGrantSQLParams{
		Allowlist:    allowlist,
		RoleName:     "gongmcp_redacted_reader",
		DatabaseName: "gongctl",
	})
	if err != nil {
		t.Fatalf("BuildScopedReaderGrantSQL returned error: %v", err)
	}
	for _, want := range []string{
		`GRANT SELECT ("call_id", "context_present", "duration_seconds", "parties_count", "started_at", "title") ON TABLE public."calls" TO "gongmcp_redacted_reader";`,
		`GRANT SELECT ("account_count", "account_industry", "call_date", "call_id", "direction", "duration_seconds", "lifecycle_bucket", "lifecycle_confidence", "likely_voicemail_or_ivr", "opportunity_count", "opportunity_stage", "scope", "started_at", "system", "transcript_present", "transcript_status") ON TABLE public."call_facts" TO "gongmcp_redacted_reader";`,
		`GRANT SELECT ("call_id", "id", "object_key", "object_type") ON TABLE public."gongmcp_call_context_objects" TO "gongmcp_redacted_reader";`,
		`GRANT SELECT ("call_id", "field_label", "field_name", "field_populated", "field_type", "id", "object_key") ON TABLE public."gongmcp_call_context_fields" TO "gongmcp_redacted_reader";`,
		`GRANT SELECT ("active", "kind", "name", "object_id", "updated_at") ON TABLE public."gong_settings" TO "gongmcp_redacted_reader";`,
		`GRANT EXECUTE ON FUNCTION public.gongmcp_crm_field_value_search(text, text, text, integer, boolean, boolean) TO "gongmcp_redacted_reader";`,
		`GRANT EXECUTE ON FUNCTION public.gongmcp_scorecard_activity_summary(text, integer) TO "gongmcp_redacted_reader";`,
		`GRANT EXECUTE ON FUNCTION public.gongmcp_missing_transcripts(text, text, text, text, text, text, text, text, integer) TO "gongmcp_redacted_reader";`,
		`GRANT EXECUTE ON FUNCTION public.gongmcp_business_analysis_calls(text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, boolean, integer, text) TO "gongmcp_redacted_reader";`,
		`GRANT EXECUTE ON FUNCTION public.gongmcp_business_analysis_evidence(text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, boolean, integer, text) TO "gongmcp_redacted_reader";`,
		`GRANT EXECUTE ON FUNCTION public.gongmcp_search_transcript_quotes_with_attribution(text, text, text, text, text, text, text, text, text, text, text, integer) TO "gongmcp_redacted_reader";`,
	} {
		if !strings.Contains(sql, want) {
			t.Fatalf("generated SQL missing %q\n%s", want, sql)
		}
	}
	for _, forbidden := range []string{
		`GRANT EXECUTE ON FUNCTION public.gongmcp_business_analysis_calls_sanitized`,
		`GRANT EXECUTE ON FUNCTION public.gongmcp_business_analysis_evidence_sanitized`,
		`ON TABLE public."transcript_segments"`,
		`ON TABLE public."call_context_fields"`,
		`ON TABLE public."scorecard_activity"`,
		`"raw_json"`,
		`"raw_sha256"`,
		`"field_value_text"`,
		`"highlight_text"`,
		`CREATE ROLE`,
		`PASSWORD`,
	} {
		if strings.Contains(sql, forbidden) {
			t.Fatalf("generated SQL included forbidden %q\n%s", forbidden, sql)
		}
	}
}

func TestBuildScopedReaderGrantSQLAnalystGrantsCallDrilldownEvidenceFunction(t *testing.T) {
	allowlist := []string{
		"get_sync_status",
		"list_crm_object_types",
		"list_crm_fields",
		"get_business_profile",
		"list_business_concepts",
		"list_unmapped_crm_fields",
		"analyze_late_stage_crm_signals",
		"opportunities_missing_transcripts",
		"search_transcripts_by_crm_context",
		"opportunity_call_summary",
		"crm_field_population_matrix",
		"list_lifecycle_buckets",
		"summarize_calls_by_lifecycle",
		"prioritize_transcripts_by_lifecycle",
		"compare_lifecycle_crm_fields",
		"summarize_call_facts",
		"rank_transcript_backlog",
		"search_transcript_segments",
		"search_transcripts_by_call_facts",
		"search_transcript_quotes_with_attribution",
		"list_scorecards",
		"get_scorecard",
		"build_call_cohort",
		"inspect_call_cohort",
		"list_call_cohorts",
		"compare_call_cohorts",
		"search_calls_by_filters",
		"summarize_calls_by_filters",
		"search_transcripts_by_filters",
		"discover_themes_in_cohort",
		"summarize_themes_by_dimension",
		"compare_themes_over_time",
		"compare_themes_by_segment",
		"extract_theme_quotes",
		"search_quotes_in_cohort",
		"rank_quotes_for_sales_use",
		"build_quote_pack",
		"list_call_ai_highlights",
		"call_drilldown",
		"compare_theme_outcomes",
		"summarize_pipeline_progression_by_theme",
		"summarize_loss_reasons_by_theme",
		"compare_won_lost_theme_patterns",
		"summarize_themes_by_persona",
		"summarize_themes_by_industry",
		"rank_personas_by_insight_quality",
		"diagnose_attribution_coverage",
		"generate_sales_hooks_from_themes",
		"generate_outreach_sequence_inputs",
		"recommend_target_personas_and_industries",
		"build_theme_brief",
		"score_cohort_evidence_quality",
		"explain_analysis_limitations",
		"suggest_filter_refinements",
	}
	sql, err := BuildScopedReaderGrantSQL(ScopedReaderGrantSQLParams{
		Allowlist:    allowlist,
		RoleName:     "gongmcp_analyst_reader",
		DatabaseName: "gongctl",
	})
	if err != nil {
		t.Fatalf("BuildScopedReaderGrantSQL returned error: %v", err)
	}
	if !strings.Contains(sql, `GRANT EXECUTE ON FUNCTION public.gongmcp_call_drilldown_transcript_evidence(text, text, integer) TO "gongmcp_analyst_reader";`) {
		t.Fatalf("generated SQL missing call-drilldown evidence grant:\n%s", sql)
	}
	if !strings.Contains(sql, `GRANT EXECUTE ON FUNCTION public.gongmcp_resolve_call_ref(text) TO "gongmcp_analyst_reader";`) {
		t.Fatalf("generated SQL missing call-ref resolver grant:\n%s", sql)
	}
	if !strings.Contains(sql, `GRANT EXECUTE ON FUNCTION public.gongmcp_call_detail(text) TO "gongmcp_analyst_reader";`) {
		t.Fatalf("generated SQL missing call detail helper grant:\n%s", sql)
	}
	for _, line := range strings.Split(sql, "\n") {
		if strings.Contains(line, `ON TABLE public."calls"`) && strings.Contains(line, `"call_id"`) {
			t.Fatalf("generated SQL granted direct calls.call_id instead of resolver function:\n%s", sql)
		}
	}
}

func TestBuildScopedReaderGrantSQLRejectsUnsafeIdentifiers(t *testing.T) {
	allowlist := []string{"get_sync_status", "summarize_call_facts", "summarize_calls_by_lifecycle", "rank_transcript_backlog"}
	for _, tc := range []struct {
		name     string
		roleName string
		dbName   string
	}{
		{name: "role injection", roleName: `reader"; DROP ROLE writer; --`, dbName: "gongctl"},
		{name: "database dash", roleName: "gongmcp_reader", dbName: "gongctl-prod"},
		{name: "role starts digit", roleName: "1_reader", dbName: "gongctl"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			_, err := BuildScopedReaderGrantSQL(ScopedReaderGrantSQLParams{
				Allowlist:    allowlist,
				RoleName:     tc.roleName,
				DatabaseName: tc.dbName,
			})
			if err == nil {
				t.Fatal("BuildScopedReaderGrantSQL accepted unsafe identifier")
			}
		})
	}
}
