package postgres

import (
	"strings"
	"testing"
)

func TestBuildScopedReaderGrantSQLBusinessPilot(t *testing.T) {
	allowlist := []string{"get_sync_status", "summarize_call_facts", "summarize_calls_by_lifecycle", "rank_transcript_backlog"}
	sql, err := BuildScopedReaderGrantSQL(ScopedReaderGrantSQLParams{
		Allowlist:    allowlist,
		RoleName:     "gongmcp_business_pilot_reader",
		DatabaseName: "gongctl",
	})
	if err != nil {
		t.Fatalf("BuildScopedReaderGrantSQL returned error: %v", err)
	}
	for _, want := range []string{
		`-- Generated by gongctl/gongmcp scoped-reader grant helper.`,
		`-- Apply to a fresh NOINHERIT role; revoke stale table/function grants before reusing an existing role.`,
		`-- This is a gongmcp service credential, not an analyst SQL login: selected SECURITY DEFINER functions can return minimized call IDs/titles to direct SQL holders.`,
		`-- This grant block supports the business-pilot scoped reader for profile-backed lifecycle analysis; use the compatibility reader role for builtin lifecycle-source analysis until a sanitized builtin SQL surface is available.`,
		`GRANT CONNECT ON DATABASE "gongctl" TO "gongmcp_business_pilot_reader";`,
		`GRANT USAGE ON SCHEMA "public" TO "gongmcp_business_pilot_reader";`,
		`GRANT SELECT ("parties_count", "started_at") ON TABLE public."calls" TO "gongmcp_business_pilot_reader";`,
		`GRANT SELECT ("transcript_status") ON TABLE public."call_facts" TO "gongmcp_business_pilot_reader";`,
		`GRANT EXECUTE ON FUNCTION public.gongmcp_profile_call_fact_summary(bigint, text, text, text, text, text, text, text, integer) TO "gongmcp_business_pilot_reader";`,
		`COMMIT;`,
	} {
		if !strings.Contains(sql, want) {
			t.Fatalf("generated SQL missing %q\n%s", want, sql)
		}
	}
	for _, forbidden := range []string{
		`PASSWORD`,
		`CREATE ROLE`,
		`"call_id", "title"`,
		`public.gongmcp_missing_transcripts`,
		`field_values_json`,
	} {
		if strings.Contains(sql, forbidden) {
			t.Fatalf("generated SQL included forbidden %q\n%s", forbidden, sql)
		}
	}
	for _, line := range strings.Split(sql, "\n") {
		if strings.Contains(line, `ON TABLE public."calls"`) && strings.Contains(line, `"call_id"`) {
			t.Fatalf("generated SQL included calls.call_id grant\n%s", sql)
		}
		if strings.Contains(line, `ON TABLE public."calls"`) && strings.Contains(line, `"title"`) {
			t.Fatalf("generated SQL included calls.title grant\n%s", sql)
		}
		if strings.Contains(line, `ON TABLE public."call_facts"`) && strings.Contains(line, `"call_id"`) {
			t.Fatalf("generated SQL included call_facts.call_id grant\n%s", sql)
		}
		if strings.Contains(line, `ON TABLE public."call_facts"`) && strings.Contains(line, `"title"`) {
			t.Fatalf("generated SQL included call_facts.title grant\n%s", sql)
		}
	}
}

func TestBuildScopedReaderGrantSQLRejectsUnsupportedSurface(t *testing.T) {
	if _, err := BuildScopedReaderGrantSQL(ScopedReaderGrantSQLParams{
		Allowlist:    []string{"get_sync_status", "search_calls"},
		RoleName:     "gongmcp_reader",
		DatabaseName: "gongctl",
	}); err == nil {
		t.Fatal("BuildScopedReaderGrantSQL accepted unsupported non-business-pilot surface")
	}
}

func TestBuildScopedReaderGrantSQLRejectsUnsafeIdentifiers(t *testing.T) {
	allowlist := []string{"get_sync_status", "summarize_call_facts", "summarize_calls_by_lifecycle", "rank_transcript_backlog"}
	for _, tc := range []struct {
		name     string
		roleName string
		dbName   string
	}{
		{name: "role injection", roleName: `reader"; DROP ROLE writer; --`, dbName: "gongctl"},
		{name: "database dash", roleName: "gongmcp_reader", dbName: "gongctl-prod"},
		{name: "role starts digit", roleName: "1_reader", dbName: "gongctl"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			_, err := BuildScopedReaderGrantSQL(ScopedReaderGrantSQLParams{
				Allowlist:    allowlist,
				RoleName:     tc.roleName,
				DatabaseName: tc.dbName,
			})
			if err == nil {
				t.Fatal("BuildScopedReaderGrantSQL accepted unsafe identifier")
			}
		})
	}
}
