package postgres

import (
	"fmt"
	"sort"
	"strings"
)

type ScopedReaderGrantSQLParams struct {
	Allowlist    []string
	RoleName     string
	DatabaseName string
	Generator    string
	CreateRole   bool
}

func ReadOnlyOptionsForToolAllowlist(allowlist []string) ReadOnlyOptions {
	signatures := FunctionSignaturesForTools(allowlist)
	options := ReadOnlyOptions{
		RequiredFunctionSignatures:     signatures,
		AllowedFunctionSignatures:      signatures,
		EnforceAllowedFunctionBoundary: true,
	}
	if BusinessPilotScopedColumns(allowlist) {
		columns := BusinessPilotColumnSelectGrants()
		options.RequiredColumnSelectGrants = columns
		options.AllowedColumnSelectGrants = columns
		options.EnforceAllowedColumnBoundary = true
	}
	return options
}

func BuildScopedReaderGrantSQL(params ScopedReaderGrantSQLParams) (string, error) {
	options := ReadOnlyOptionsForToolAllowlist(params.Allowlist)
	if !options.EnforceAllowedColumnBoundary || !BusinessPilotScopedColumns(params.Allowlist) {
		return "", fmt.Errorf("scoped reader grant SQL currently supports only the reviewed business-pilot scoped reader surface")
	}
	roleIdent, err := quotePostgresIdentifier(params.RoleName)
	if err != nil {
		return "", fmt.Errorf("invalid role name: %w", err)
	}
	dbIdent, err := quotePostgresIdentifier(params.DatabaseName)
	if err != nil {
		return "", fmt.Errorf("invalid database name: %w", err)
	}

	var b strings.Builder
	generator := strings.TrimSpace(params.Generator)
	if generator == "" {
		generator = "gongctl/gongmcp scoped-reader grant helper"
	}
	b.WriteString("-- Generated by ")
	b.WriteString(generator)
	b.WriteString(".\n")
	b.WriteString("-- Create credentials outside this grant block using your secret manager.\n")
	b.WriteString("-- Role expected before running this block: ")
	b.WriteString(roleIdent)
	b.WriteString("\n")
	b.WriteString("BEGIN;\n")
	if params.CreateRole {
		b.WriteString("CREATE ROLE ")
		b.WriteString(roleIdent)
		b.WriteString(" LOGIN;\n")
	}
	b.WriteString("REVOKE CREATE ON SCHEMA \"public\" FROM ")
	b.WriteString(roleIdent)
	b.WriteString(";\n")
	b.WriteString("GRANT CONNECT ON DATABASE ")
	b.WriteString(dbIdent)
	b.WriteString(" TO ")
	b.WriteString(roleIdent)
	b.WriteString(";\n")
	b.WriteString("GRANT USAGE ON SCHEMA \"public\" TO ")
	b.WriteString(roleIdent)
	b.WriteString(";\n")

	for _, grant := range groupedColumnGrants(options.RequiredColumnSelectGrants) {
		b.WriteString("GRANT SELECT (")
		for i, column := range grant.Columns {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(column)
		}
		b.WriteString(") ON TABLE ")
		b.WriteString(grant.Table)
		b.WriteString(" TO ")
		b.WriteString(roleIdent)
		b.WriteString(";\n")
	}
	signatures := dedupeStrings(options.RequiredFunctionSignatures)
	sort.Strings(signatures)
	for _, signature := range signatures {
		b.WriteString("GRANT EXECUTE ON FUNCTION ")
		b.WriteString(signature)
		b.WriteString(" TO ")
		b.WriteString(roleIdent)
		b.WriteString(";\n")
	}
	b.WriteString("COMMIT;\n")
	return b.String(), nil
}

func GovernanceFunctionSignatures() []string {
	return []string{
		"public.gongmcp_governance_data_fingerprint()",
		"public.gongmcp_governance_policy_state(text)",
		"public.gongmcp_governance_suppressed_call_ids(text)",
	}
}

func FunctionSignaturesForTools(allowlist []string) []string {
	profileReadinessFunctions := []string{
		"public.gongmcp_active_business_profile()",
		"public.gongmcp_profile_call_fact_cache_meta(bigint, text)",
		"public.gongmcp_profile_data_fingerprint()",
	}
	profileRowsFunctions := append(copyPostgresFunctionSignatures(profileReadinessFunctions),
		"public.gongmcp_profile_call_fact_cache(bigint, text)",
	)
	profileSummaryFunctions := append(copyPostgresFunctionSignatures(profileReadinessFunctions),
		"public.gongmcp_profile_call_fact_summary(bigint, text, text, text, text, text, text, text, integer)",
	)
	businessAnalysisCoreFunctions := []string{
		"public.gongmcp_business_analysis_calls(text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, integer)",
		"public.gongmcp_business_analysis_summary(text, text, text, text, text, text, text, text, text, text, text, text, text, text, text)",
	}
	businessAnalysisEvidenceFunctions := append(copyPostgresFunctionSignatures(businessAnalysisCoreFunctions),
		"public.gongmcp_business_analysis_evidence(text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, integer)",
	)
	businessAnalysisDimensionFunctions := append(copyPostgresFunctionSignatures(businessAnalysisCoreFunctions),
		"public.gongmcp_business_analysis_dimension(text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, integer)",
	)
	functionsByTool := map[string][]string{
		"analyze_late_stage_crm_signals": {
			"public.gongmcp_late_stage_call_counts(text, text, text)",
			"public.gongmcp_late_stage_stage_counts(text, text, text)",
			"public.gongmcp_late_stage_signal_inventory(text, text, text, integer, boolean)",
		},
		"build_call_cohort": businessAnalysisCoreFunctions,
		"compare_lifecycle_crm_fields": {
			"public.gongmcp_compare_lifecycle_crm_fields(text, text, text, integer)",
		},
		"crm_field_population_matrix": {
			"public.gongmcp_crm_field_population_matrix(text, text, integer)",
		},
		"diagnose_attribution_coverage": businessAnalysisCoreFunctions,
		"discover_themes_in_cohort":     businessAnalysisEvidenceFunctions,
		"explain_analysis_limitations":  businessAnalysisCoreFunctions,
		"extract_theme_quotes":          businessAnalysisEvidenceFunctions,
		"get_sync_status": {
			"public.gongmcp_active_business_profile()",
			"public.gongmcp_profile_call_fact_cache_meta(bigint, text)",
			"public.gongmcp_profile_data_fingerprint()",
			"public.gongmcp_scorecard_activity_totals()",
		},
		"get_business_profile": {
			"public.gongmcp_active_business_profile()",
		},
		"get_scorecard": {
			"public.gongmcp_scorecard_detail(text)",
		},
		"inspect_call_cohort": businessAnalysisCoreFunctions,
		"list_business_concepts": {
			"public.gongmcp_active_business_profile()",
		},
		"list_crm_object_types": {
			"public.gongmcp_crm_object_type_summary()",
		},
		"list_lifecycle_buckets": profileReadinessFunctions,
		"list_scorecards": {
			"public.gongmcp_scorecards(boolean, integer)",
		},
		"list_unmapped_crm_fields": append([]string{
			"public.gongmcp_unmapped_crm_field_inventory(integer)",
		}, profileReadinessFunctions...),
		"missing_transcripts": {
			"public.gongmcp_missing_transcripts(text, text, text, text, text, text, text, text, integer)",
		},
		"opportunities_missing_transcripts": {
			"public.gongmcp_opportunities_missing_transcripts(text, integer)",
		},
		"opportunity_call_summary": {
			"public.gongmcp_opportunity_call_summary(text, integer)",
		},
		"prioritize_transcripts_by_lifecycle": profileRowsFunctions,
		"rank_transcript_backlog":             profileRowsFunctions,
		"score_cohort_evidence_quality":       businessAnalysisCoreFunctions,
		"search_calls_by_filters":             businessAnalysisCoreFunctions,
		"search_calls_by_lifecycle":           profileRowsFunctions,
		"search_crm_field_values": {
			"public.gongmcp_crm_field_value_search(text, text, text, integer, boolean, boolean)",
		},
		"search_quotes_in_cohort": businessAnalysisEvidenceFunctions,
		"search_transcript_quotes_with_attribution": {
			"public.gongmcp_search_transcript_quotes_with_attribution(text, text, text, text, text, text, text, text, text, text, text, integer)",
		},
		"search_transcript_segments": {
			"public.gongmcp_search_transcript_segments(text, integer)",
			"public.gongmcp_search_transcript_segments_by_call_facts(text, text, text, text, text, text, text, integer)",
		},
		"search_transcripts_by_call_facts": {
			"public.gongmcp_search_transcript_segments_by_call_facts(text, text, text, text, text, text, text, integer)",
		},
		"search_transcripts_by_crm_context": {
			"public.gongmcp_search_transcript_segments_by_crm_context(text, text, text, integer)",
		},
		"search_transcripts_by_filters": businessAnalysisEvidenceFunctions,
		"suggest_filter_refinements":    businessAnalysisCoreFunctions,
		"summarize_call_facts":          profileSummaryFunctions,
		"summarize_calls_by_filters":    businessAnalysisDimensionFunctions,
		"summarize_calls_by_lifecycle":  profileRowsFunctions,
		"summarize_scorecard_activity": {
			"public.gongmcp_scorecard_activity_summary(text, integer)",
			"public.gongmcp_scorecard_activity_totals()",
		},
		"summarize_themes_by_dimension": businessAnalysisDimensionFunctions,
	}
	var signatures []string
	for _, name := range allowlist {
		signatures = append(signatures, functionsByTool[name]...)
	}
	return signatures
}

func BusinessPilotScopedColumns(allowlist []string) bool {
	want := map[string]struct{}{
		"get_sync_status":              {},
		"summarize_call_facts":         {},
		"summarize_calls_by_lifecycle": {},
		"rank_transcript_backlog":      {},
	}
	if len(allowlist) != len(want) {
		return false
	}
	for _, name := range allowlist {
		if _, ok := want[name]; !ok {
			return false
		}
	}
	return true
}

func BusinessPilotColumnSelectGrants() []ColumnSelectGrant {
	grants := []ColumnSelectGrant{
		{Table: "gongctl_schema_migrations", Column: "version"},
		{Table: "calls", Column: "started_at"},
		{Table: "calls", Column: "parties_count"},
		{Table: "users", Column: "user_id"},
		{Table: "users", Column: "title"},
		{Table: "transcripts", Column: "segment_count"},
		{Table: "gongmcp_call_context_objects", Column: "id"},
		{Table: "gongmcp_call_context_objects", Column: "call_id"},
		{Table: "gongmcp_call_context_objects", Column: "object_key"},
		{Table: "gongmcp_call_context_objects", Column: "object_type"},
		{Table: "gongmcp_call_context_fields", Column: "id"},
		{Table: "gongmcp_call_context_fields", Column: "call_id"},
		{Table: "gongmcp_call_context_fields", Column: "object_key"},
		{Table: "gongmcp_call_context_fields", Column: "field_name"},
		{Table: "gongmcp_call_context_fields", Column: "field_label"},
		{Table: "gongmcp_call_context_fields", Column: "field_type"},
		{Table: "gongmcp_call_context_fields", Column: "field_populated"},
		{Table: "crm_integrations", Column: "integration_id"},
		{Table: "crm_schema_objects", Column: "object_type"},
		{Table: "crm_schema_fields", Column: "field_name"},
		{Table: "gong_settings", Column: "kind"},
		{Table: "call_facts", Column: "transcript_status"},
		{Table: "postgres_read_model_state", Column: "model_name"},
		{Table: "postgres_read_model_state", Column: "model_version"},
		{Table: "postgres_read_model_state", Column: "rebuilt_at"},
		{Table: "postgres_read_model_state", Column: "call_count"},
		{Table: "postgres_read_model_state", Column: "fact_count"},
		{Table: "postgres_read_model_state", Column: "missing_fact_call_count"},
		{Table: "postgres_read_model_state", Column: "orphan_fact_count"},
		{Table: "postgres_read_model_state", Column: "stale_reason"},
		{Table: "postgres_read_model_state", Column: "updated_at"},
	}
	for _, column := range []string{"id", "scope", "sync_key", "cursor", "from_value", "to_value", "request_context", "status", "started_at", "finished_at", "records_seen", "records_written", "error_text"} {
		grants = append(grants, ColumnSelectGrant{Table: "gongmcp_sync_runs", Column: column})
	}
	for _, column := range []string{"sync_key", "scope", "cursor", "last_run_id", "last_status", "last_error", "last_success_at", "updated_at"} {
		grants = append(grants, ColumnSelectGrant{Table: "gongmcp_sync_state", Column: column})
	}
	return grants
}

func copyPostgresFunctionSignatures(signatures []string) []string {
	out := make([]string, len(signatures))
	copy(out, signatures)
	return out
}

func dedupeStrings(values []string) []string {
	seen := make(map[string]struct{}, len(values))
	out := make([]string, 0, len(values))
	for _, value := range values {
		if _, ok := seen[value]; ok {
			continue
		}
		seen[value] = struct{}{}
		out = append(out, value)
	}
	return out
}

type groupedPostgresColumnGrant struct {
	Table   string
	Columns []string
}

func groupedColumnGrants(grants []ColumnSelectGrant) []groupedPostgresColumnGrant {
	byTable := make(map[string][]string)
	for _, grant := range grants {
		table, err := quotePostgresIdentifier(grant.Table)
		if err != nil {
			panic(fmt.Sprintf("invalid built-in postgres grant table %q: %v", grant.Table, err))
		}
		column, err := quotePostgresIdentifier(grant.Column)
		if err != nil {
			panic(fmt.Sprintf("invalid built-in postgres grant column %q: %v", grant.Column, err))
		}
		byTable[table] = append(byTable[table], column)
	}
	tables := make([]string, 0, len(byTable))
	for table := range byTable {
		tables = append(tables, table)
	}
	sort.Strings(tables)
	out := make([]groupedPostgresColumnGrant, 0, len(tables))
	for _, table := range tables {
		columns := byTable[table]
		sort.Strings(columns)
		out = append(out, groupedPostgresColumnGrant{Table: table, Columns: columns})
	}
	return out
}

func quotePostgresIdentifier(name string) (string, error) {
	trimmed := strings.TrimSpace(name)
	if trimmed == "" {
		return "", fmt.Errorf("identifier is empty")
	}
	if len(trimmed) > 63 {
		return "", fmt.Errorf("identifier is longer than 63 bytes")
	}
	for i, r := range trimmed {
		if r > 127 {
			return "", fmt.Errorf("identifier must use ASCII letters, digits, or underscore")
		}
		if i == 0 {
			if (r < 'A' || r > 'Z') && (r < 'a' || r > 'z') && r != '_' {
				return "", fmt.Errorf("identifier must start with a letter or underscore")
			}
			continue
		}
		if (r < 'A' || r > 'Z') && (r < 'a' || r > 'z') && (r < '0' || r > '9') && r != '_' {
			return "", fmt.Errorf("identifier must use ASCII letters, digits, or underscore")
		}
	}
	return `"` + trimmed + `"`, nil
}
